### ISSUE TITLE
NameError: name 'parse_qs' is not defined.

### ISSUE THREAD

**Issue by whytox** [yausername/youtubedl-android#101]
Hi guys, I'm on a Android 10 device, testing the example app before trying to build my own one, but I'm having some problems:
- First, when I try to download a video, I get the error: unable to extract video data, with this log

`E/DownloadingExample: failed to download
    com.yausername.youtubedl_android.YoutubeDLException: ERROR: -14gm0fBFho: YouTube said: Unable to extract video data`
    
        at com.yausername.youtubedl_android.YoutubeDL.execute(YoutubeDL.java:201)
        at com.yausername.youtubedl_android_example.DownloadingExampleActivity.lambda$startDownload$0$DownloadingExampleActivity(DownloadingExampleActivity.java:116)
        at com.yausername.youtubedl_android_example.-$$Lambda$DownloadingExampleActivity$DIqcJ_vtApVhyONpHFiA5nyofXo.call(Unknown Source:4)
        at io.reactivex.internal.operators.observable.ObservableFromCallable.subscribeActual(ObservableFromCallable.java:42)
        at io.reactivex.Observable.subscribe(Observable.java:12030)
        at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:579)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)`
- so I update the youtube-dl binaries using the relative button
- But doing so I get a python name error, saying: "parse_qs is not define"
- I am using the following additional parameters to the request, (but also without I get the same error): "-f best"

Python error stack trace:

> E/DownloadingExample: failed to download
>     com.yausername.youtubedl_android.YoutubeDLException: Traceback (most recent call last):
>       File "/data/user/0/com.yausername.youtubedl_android_example/no_backup/youtubedl-android/youtube-dl/__main__.py", line 19, in <module>
>         youtube_dl.main()
>       File "/data/data/com.yausername.youtubedl_android_example/no_backup/youtubedl-android/youtube-dl/youtube_dl/__init__.py", line 475, in main
>         _real_main(argv)
>       File "/data/data/com.yausername.youtubedl_android_example/no_backup/youtubedl-android/youtube-dl/youtube_dl/__init__.py", line 465, in _real_main
>         retcode = ydl.download(all_urls)
>       File "/data/data/com.yausername.youtubedl_android_example/no_backup/youtubedl-android/youtube-dl/youtube_dl/YoutubeDL.py", line 2059, in download
>         res = self.extract_info(
>       File "/data/data/com.yausername.youtubedl_android_example/no_backup/youtubedl-android/youtube-dl/youtube_dl/YoutubeDL.py", line 791, in extract_info
>         if not ie.suitable(url):
>       File "/data/data/com.yausername.youtubedl_android_example/no_backup/youtubedl-android/youtube-dl/youtube_dl/extractor/lazy_extractors.py", line 2085, in suitable
>         return False if YoutubeIE.suitable(url) else super(
>       File "/data/data/com.yausername.youtubedl_android_example/no_backup/youtubedl-android/youtube-dl/youtube_dl/extractor/lazy_extractors.py", line 5612, in suitable
>         qs = parse_qs(url)
>     NameError: name 'parse_qs' is not defined

Does maybe the lib need to be updated to be compatible the last youtube-dl version? I have no clue about this problem, any suggestion will be appreciated. Thank you.

## Update
This could be a youtube-dl issue, not yours, https://github.com/ytdl-org/youtube-dl/issues/28780

**Comment by xibr** [comment]
Related to [youtubedl-lazy](https://github.com/yausername/youtubedl-lazy) See [https://github.com/yausername/youtubedl-lazy/issues/7](https://github.com/yausername/youtubedl-lazy/issues/7)

**Comment by whytox** [comment]
Thank you xibr!
