### ISSUE TITLE
libpython.zip.so: open failed: ENOENT (No such file or directory)

### ISSUE THREAD

**Issue by jppcel** [yausername/youtubedl-android#105]
Hello,

I am having a problem with this library on an application.

When i use, i have an exception with say:
04-23 03:28:13.943 7149-7573 E/FBYdl: failed to initialize youtubedl-android
    com.yausername.youtubedl_android.YoutubeDLException: failed to initialize
...
    Caused by: java.io.FileNotFoundException: .../**lib/x86/libpython.zip.so: open failed: ENOENT (No such file or directory)**

What i am doing wrong to it happens?

I am have using the last version of this library, with `minSdkVersion 23`, `compileSdkVersion 30` and `targetSdkVersion 28`, if it helps.

Thanks for the help.

**Comment by xibr** [comment]
Did you add this code in `onCreate`?

```
​try​ {
    ​YoutubeDL​.​getInstance()​.​init(getApplication());
} ​catch​ (​YoutubeDLException​ e) {
    ​Log​.​e(​TAG​, ​"​failed to initialize youtubedl-android​"​, e);
}
```

**Comment by jppcel** [comment]
@xibr Yes, i did it.

I tried to use in a Memu emulator and it works fine, but when i try on my cellphone and in the Android Emulator default, the problem occours.

Memu emulator = Android 7.1
Android emulator = Android 6.0
Cellphone = Android 8.1

**Comment by xibr** [comment]
Sorry for the late response, does this example [https://github.com/yausername/youtubedl-android/releases/tag/0.12.1](https://github.com/yausername/youtubedl-android/releases/tag/0.12.1)  work on your phone?

**Comment by xibr** [comment]
@jppcel make sure you have add this `android:extractNativeLibs="true"` in your app's manifest like this [https://github.com/yausername/youtubedl-android/blob/658ea9808b825a6b73caa7411dee34d00d0d723e/app/src/main/AndroidManifest.xml#L16](https://github.com/yausername/youtubedl-android/blob/658ea9808b825a6b73caa7411dee34d00d0d723e/app/src/main/AndroidManifest.xml#L16)

when i set it to false i have same error, see the error log
```
2021-05-02 21:46:45.551 14726-14726/com.yausername.youtubedl_android_example E/App: failed to initialize youtubedl-android
    com.yausername.youtubedl_android.YoutubeDLException: failed to initialize
        at com.yausername.youtubedl_android.YoutubeDL.initPython(YoutubeDL.java:103)
        at com.yausername.youtubedl_android.YoutubeDL.init(YoutubeDL.java:74)
        at com.yausername.youtubedl_android_example.App.initLibraries(App.java:59)
        at com.yausername.youtubedl_android_example.App.lambda$1OACUsDHOonyzawKfkQjnuBwp-g(Unknown Source:0)
        at com.yausername.youtubedl_android_example.-$$Lambda$App$1OACUsDHOonyzawKfkQjnuBwp-g.run(Unknown Source:2)
        at io.reactivex.internal.operators.completable.CompletableFromAction.subscribeActual(CompletableFromAction.java:34)
        at io.reactivex.Completable.subscribe(Completable.java:2171)
        at io.reactivex.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.run(CompletableSubscribeOn.java:64)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:579)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.io.FileNotFoundException: /data/app/com.yausername.youtubedl_android_example-MluvK5WNAJg19IeZ4BsgkA==/lib/arm64/libpython.zip.so: open failed: ENOENT (No such file or directory)
```

**Comment by praty007** [comment]
Did you manage to find the fix? 

I am having the same issue. I noticed that I am getting ENOENT when trying to access /lib/arm64/libpython.zip.so

In the apk, I found that there is no dir called arm64. The binaries for arm64 are stored in /lib/arm64-v8a, similarly for armeabi, they are stored in /lib/armeabi-v7a

Please check out https://developer.android.com/ndk/guides/abis.

**Comment by praty007** [comment]
What went wrong: In the main app's AndroidManifest.xml file, I added `android:extractNativeLibs="true"` to `<manifest>` tag.
FIX: Add `android:extractNativeLibs="true"` to `<application>` tag. See [https://github.com/yausername/youtubedl-android/blob/master/app/src/main/AndroidManifest.xml](url)

It's essentially a non-issue.
I am a beginner with android studio and Kotlin/Java in general. Made a rookie mistake. I hope @jppcel did the same.

**Comment by jppcel** [comment]
> 
> 
> @jppcel make sure you have add this `android:extractNativeLibs="true"` in your app's manifest like this
> 
> https://github.com/yausername/youtubedl-android/blob/658ea9808b825a6b73caa7411dee34d00d0d723e/app/src/main/AndroidManifest.xml#L16
> 
> when i set it to false i have same error, see the error log
> 
> ```
> 2021-05-02 21:46:45.551 14726-14726/com.yausername.youtubedl_android_example E/App: failed to initialize youtubedl-android
>     com.yausername.youtubedl_android.YoutubeDLException: failed to initialize
>         at com.yausername.youtubedl_android.YoutubeDL.initPython(YoutubeDL.java:103)
>         at com.yausername.youtubedl_android.YoutubeDL.init(YoutubeDL.java:74)
>         at com.yausername.youtubedl_android_example.App.initLibraries(App.java:59)
>         at com.yausername.youtubedl_android_example.App.lambda$1OACUsDHOonyzawKfkQjnuBwp-g(Unknown Source:0)
>         at com.yausername.youtubedl_android_example.-$$Lambda$App$1OACUsDHOonyzawKfkQjnuBwp-g.run(Unknown Source:2)
>         at io.reactivex.internal.operators.completable.CompletableFromAction.subscribeActual(CompletableFromAction.java:34)
>         at io.reactivex.Completable.subscribe(Completable.java:2171)
>         at io.reactivex.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.run(CompletableSubscribeOn.java:64)
>         at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:579)
>         at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
>         at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
>         at java.lang.Thread.run(Thread.java:919)
>      Caused by: java.io.FileNotFoundException: /data/app/com.yausername.youtubedl_android_example-MluvK5WNAJg19IeZ4BsgkA==/lib/arm64/libpython.zip.so: open failed: ENOENT (No such file or directory)
> ```

Hello,
With that the problem was solved.
