### ISSUE TITLE
Error while updating YoutubeDL binary

### ISSUE THREAD

**Issue by naveedhassan913** [yausername/youtubedl-android#12]
```
java.lang.IllegalArgumentException: position=0 count=9223372036854775807
	at java.nio.FileChannelImpl.transferFrom(FileChannelImpl.java:370)
	at com.yausername.youtubedl_android.YoutubeDLUpdater.download(YoutubeDLUpdater.java:110)
	at com.yausername.youtubedl_android.YoutubeDLUpdater.update(YoutubeDLUpdater.java:36)
	at com.yausername.youtubedl_android.YoutubeDL.updateYoutubeDL(YoutubeDL.java:190)
	at com.mycompany.myapp4.MainActivity$100000000.run(MainActivity.java:41)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)
```

_Sent from my HOT 4 PRO using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yausername** [comment]
Hi,
Thanks for reporting the issue. Sorry for the late response.
It has been closed in 0.6.1
Let me know if you still face any issue.
