### ISSUE TITLE
youtubedl cant be get initialized and the app is crashed. 

### ISSUE THREAD

**Issue by clonedSemicolon** [yausername/youtubedl-android#135]
While initializing the youtubedl the following error is generated: 

```
java.lang.RuntimeException: Unable to create application acr.browser.lightning.BrowserApp: com.yausername.youtubedl_android.YoutubeDLException: failed to initialize
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6980)
	at android.app.ActivityThread.access$1500(ActivityThread.java:257)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1982)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8037)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
Caused by: com.yausername.youtubedl_android.YoutubeDLException: failed to initialize
	at com.yausername.youtubedl_android.YoutubeDL.initPython(Unknown Source:50)
	at com.yausername.youtubedl_android.YoutubeDL.init(Unknown Source:169)
	at acr.browser.lightning.BrowserApp.onCreate(:12)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1193)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6975)
	... 8 more
Caused by: java.io.FileNotFoundException: /data/app/~~5f9-GnrSmv6xt4B0lJnz_Q==/inverseai.downloader.videodownloader-ndkpoSlhJutoe5vW820BBQ==/lib/arm64/libpython.zip.so: open failed: ENOENT (No such file or directory)
	at [libcore.io](http://libcore.io/).IoBridge.open(IoBridge.java:492)
	at [java.io](http://java.io/).RandomAccessFile.<init>(RandomAccessFile.java:289)
	at n.a.a.a.a.c.j0.<init>(:1)
	at com.yausername.youtubedl_common.utils.ZipUtils.unzip(Unknown Source:2)
	at com.yausername.youtubedl_android.YoutubeDL.initPython(Unknown Source:35)
	... 12 `more`
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
	at [libcore.io](http://libcore.io/).Linux.open(Native Method)
	at [libcore.io](http://libcore.io/).ForwardingOs.open(ForwardingOs.java:166)
	at [libcore.io](http://libcore.io/).BlockGuardOs.open(BlockGuardOs.java:254)
	at [libcore.io](http://libcore.io/).ForwardingOs.open(ForwardingOs.java:166)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7911)
	at [libcore.io](http://libcore.io/).IoBridge.open(IoBridge.java:478)
```

Tried the solutions below: 

- Latest version initialized
- adding abiFilters "arm64-v8a", "armeabi-v7a", "armeabi", "mips" in the filters
- android:extractNativeLibs="true" under the <application>

**Comment by yausername** [comment]
@clonedSemicolon sorry for the late response but were you testing on an x86 based emulator by any chance?
And what was the `targetSdkVersion` ?

**Comment by GhostInTheSteiner** [comment]
I'm only able to speak for my own app, but I got the same error using those specs:

![image](https://user-images.githubusercontent.com/28263040/170049244-b7038ebf-4a57-401a-9faf-d18e573679c8.png)

I had all three variables set to API-Level 31

![image](https://user-images.githubusercontent.com/28263040/170049417-d50b02a7-e646-47ac-8f56-968c7cc9beaf.png)

I already changed some stuff on my Composition Compass app to make it (at least) work with 29 and didn't push the problematic state, otherwise I would have linked you the commit.

**Comment by yausername** [comment]
Thanks for the information.
This might get fixed by changing the code which unzips the file (maybe copying the file to a temp location before unzipping)  https://github.com/yausername/youtubedl-android/blob/a41cfdfc6952e8af13c424556292ea017f4a0706/library/src/main/java/com/yausername/youtubedl_android/YoutubeDL.java#L100
Unfortunately I don't have time to fix or test these right now.

**Comment by altush1983** [comment]
As a hotfix you can add flag
`android.bundle.enableUncompressedNativeLibs=false`
in gradle.properties.

**Comment by tashilapathum** [comment]
> As a hotfix you can add flag `android.bundle.enableUncompressedNativeLibs=false` in gradle.properties.

Thank you. This fixed the issue and lead to another message saying it's deprecated now. You can add this to `build.gradle` instead:

`android {
    packagingOptions {
        jniLibs {
            useLegacyPackaging = true
        }
    }
}`

**Comment by jialechan** [comment]
> > As a hotfix you can add flag `android.bundle.enableUncompressedNativeLibs=false` in gradle.properties.
> 
> Thank you. This fixed the issue and lead to another message saying it's deprecated now. You can add this to `build.gradle` instead:
> 
> `android { packagingOptions { jniLibs { useLegacyPackaging = true } } }`

👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍
