### ISSUE TITLE
getInfo method throws Exception for Facebook Video URL

### ISSUE THREAD

**Issue by HaXxanParhar** [yausername/youtubedl-android#164]
I have this Facebook video URL:  https://www.facebook.com/708611673740596  
I'm trying to get available formats for this video. I tested this URL using youtubedl.exe for desktop and it successfully returned the list of formats  (see the screenshot below)
![image](https://user-images.githubusercontent.com/38008190/175044027-a61edd85-67ab-404c-9204-ca95709ad00e.png)

For getting the list of formats, I'm using the getInfo() method like this:
![image](https://user-images.githubusercontent.com/38008190/175046302-8233e24d-39b0-4d6c-bc2a-1f270f3fd875.png)

This is within the thread and I'm receiving an exception for the above-mentioned Facebook video URL. You can read the stacktrace of the exception:

W/System.err: com.yausername.youtubedl_android.YoutubeDLException: ERROR: [facebook] 713657703201313: Cannot parse data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
W/System.err:     at com.yausername.youtubedl_android.YoutubeDL.execute(YoutubeDL.java:201)
W/System.err:     at com.yausername.youtubedl_android.YoutubeDL.getInfo(YoutubeDL.java:129)
W/System.err:     at com.yausername.youtubedl_android.YoutubeDL.getInfo(YoutubeDL.java:123)
W/System.err:     at com.drudotstech.videomate.GetMediaInfoThread.run(GetMediaInfoThread.java:28)

**Comment by HaXxanParhar** [comment]
My bad, the link I was passing to the thread was changed to "https://m.facebook.com/watch/?v=" + postId + "&_rdr". This is because when I call getInfo for "https://www.facebook.com/"+postId, I was getting no usable formats so I used the "/watch/?v=" link and the exception came. By usable format, I mean that which has both audio and video available. If a format only has audio or only video, I will not use it. So is there a way to recognize the usable format? What I was doing is using the Acodec and  Vcodec for recognizing if video or audio is available. And for this link https://www.facebook.com/708611673740596 every format has either Acodec null/none or Vcodec null/none. Because of this, I was getting zero usable formats. 

What I need besides the format URL:  Size (in Bytes), Resolution(480 720, etc), Extension(MP3, MP4), and Identify if the format is usable. I can get the Resolution from Width, Height. The returned extension is not precise. The returned file size is sometimes 0. and I don't know how to identify the usable format. Kindly guide me with this. I'll be very grateful to you :)
