### ISSUE TITLE
mp3 convert error

### ISSUE THREAD

**Issue by poptong** [yausername/youtubedl-android#19]
String url = "https://www.youtube.com/watch?v=7tO_eJek6D8"
String youtubeDLDir = String.valueOf(Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS));
                YoutubeDLRequest request = new YoutubeDLRequest(url);
                    
request.setOption("-o", youtubeDLDir + "/%(title)s.%(ext)s" );
                    request.setOption("--extract-audio");
                    request.setOption("--audio-format", "mp3");
                    request.setOption("--audio-quality", "0");
                    request.setOption("--embed-thumbnail");
                    request.setOption("--add-metadata");
                    request.setOption("-v");
                    request.setOption("--postprocessor-args", "-id3v2_version 3");
                    request.setOption("--no-part");
                    request.setOption("--cache-dir", youtubeDLDir + "/temp" );

--------------------------------------------------------------------------------------------

failed to download : com.yausername.youtubedl_android.YoutubeDLException: [debug] System config: []
2019-07-22 17:27:13.186 11973-11973/com.gm0723.sn02top E/PRETTY_LOGGER: │ [debug] User config: []
2019-07-22 17:27:13.187 11973-11973/com.gm0723.sn02top E/PRETTY_LOGGER: │ [debug] Custom config: []
2019-07-22 17:27:13.187 11973-11973/com.gm0723.sn02top E/PRETTY_LOGGER: │ [debug] Command-line args: ['--add-metadata', '--audio-quality', '0', '--no-part', '--postprocessor-args', '-id3v2_version 3', '-v', '--cache-dir', '/storage/emulated/0/Download/temp', '-o', '/storage/emulated/0/Download/Thank you for Goodbye Official M/V.mp3', '--embed-thumbnail', '--extract-audio', '--audio-format', 'mp3', 'https://www.youtube.com/watch?v=7tO_eJek6D8']
2019-07-22 17:27:13.187 11973-11973/com.gm0723.sn02top E/PRETTY_LOGGER: │ [debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
2019-07-22 17:27:13.187 11973-11973/com.gm0723.sn02top E/PRETTY_LOGGER: │ [debug] youtube-dl version 2019.07.16
2019-07-22 17:27:13.187 11973-11973/com.gm0723.sn02top E/PRETTY_LOGGER: │ [debug] Lazy loading extractors enabled
2019-07-22 17:27:13.187 11973-11973/com.gm0723.sn02top E/PRETTY_LOGGER: │ [debug] Python version 3.7.2 (CPython) - Linux-3.10.61-14077807-armv8l-with-libc
2019-07-22 17:27:13.188 11973-11973/com.gm0723.sn02top E/PRETTY_LOGGER: │ [debug] exe versions: ffmpeg 4.1.3, ffprobe 4.1.3
2019-07-22 17:27:13.188 11973-11973/com.gm0723.sn02top E/PRETTY_LOGGER: │ [debug] Proxy map: {}
2019-07-22 17:27:13.188 11973-11973/com.gm0723.sn02top E/PRETTY_LOGGER: │ ERROR:   Stream #0:0 -> #0:0 (copy)
2019-07-22 17:27:13.188 11973-11973/com.gm0723.sn02top E/PRETTY_LOGGER: │ Traceback (most recent call last):
2019-07-22 17:27:13.188 11973-11973/com.gm0723.sn02top E/PRETTY_LOGGER: │   File "/data/data/com.gm0723.sn02top/files/youtubedl-android/youtube-dl/youtube_dl/YoutubeDL.py", line 2054, in post_process
2019-07-22 17:27:13.188 11973-11973/com.gm0723.sn02top E/PRETTY_LOGGER: │     files_to_delete, info = pp.run(info)
2019-07-22 17:27:13.188 11973-11973/com.gm0723.sn02top E/PRETTY_LOGGER: │   File "/data/data/com.gm0723.sn02top/files/youtubedl-android/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 498, in run
2019-07-22 17:27:13.188 11973-11973/com.gm0723.sn02top E/PRETTY_LOGGER: │     self.run_ffmpeg_multiple_files(in_filenames, temp_filename, options)
2019-07-22 17:27:13.188 11973-11973/com.gm0723.sn02top E/PRETTY_LOGGER: │   File "/data/data/com.gm0723.sn02top/files/youtubedl-android/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 235, in run_ffmpeg_multiple_files
2019-07-22 17:27:13.188 11973-11973/com.gm0723.sn02top E/PRETTY_LOGGER: │     raise FFmpegPostProcessorError(msg)
2019-07-22 17:27:13.188 11973-11973/com.gm0723.sn02top E/PRETTY_LOGGER: │ youtube_dl.postprocessor.ffmpeg.FFmpegPostProcessorError:   Stream #0:0 -> #0:0 (copy)
2019-07-22 17:27:13.188 11973-11973/com.gm0723.sn02top E/PRETTY_LOGGER: │ 
2019-07-22 17:27:13.188 11973-11973/com.gm0723.sn02top E/PRETTY_LOGGER: │ 
2019-07-22 17:27:13.188 11973-11973/com.gm0723.sn02top E/PRETTY_LOGGER: │ 	at com.yausername.youtubedl_android.YoutubeDL.execute(YoutubeDL.java:178)
2019-07-22 17:27:13.189 11973-11973/com.gm0723.sn02top E/PRETTY_LOGGER: │ 	at com.gm0723.sn02top.MainActivity$11.lambda$run$0$MainActivity$11(MainActivity.java:1043)
2019-07-22 17:27:13.189 11973-11973/com.gm0723.sn02top E/PRETTY_LOGGER: │ 	at com.gm0723.sn02top.MainActivity$11$$Lambda$0.call(Unknown Source)
2019-07-22 17:27:13.189 11973-11973/com.gm0723.sn02top E/PRETTY_LOGGER: │ 	at io.reactivex.internal.operators.observable.ObservableFromCallable.subscribeActual(ObservableFromCallable.java:42)
2019-07-22 17:27:13.189 11973-11973/com.gm0723.sn02top E/PRETTY_LOGGER: │ 	at io.reactivex.Observable.subscribe(Observable.java:12030)
2019-07-22 17:27:13.189 11973-11973/com.gm0723.sn02top E/PRETTY_LOGGER: │ 	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
2019-07-22 17:27:13.189 11973-11973/com.gm0723.sn02top E/PRETTY_LOGGER: │ 	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:579)
2019-07-22 17:27:13.189 11973-11973/com.gm0723.sn02top E/PRETTY_LOGGER: │ 	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
2019-07-22 17:27:13.189 11973-11973/com.gm0723.sn02top E/PRETTY_LOGGER: │ 	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
2019-07-22 17:27:13.189 11973-11973/com.gm0723.sn02top E/PRETTY_LOGGER: │ 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
2019-07-22 17:27:13.189 11973-11973/com.gm0723.sn02top E/PRETTY_LOGGER: │ 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
2019-07-22 17:27:13.189 11973-11973/com.gm0723.sn02top E/PRETTY_LOGGER: │ 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
2019-07-22 17:27:13.189 11973-11973/com.gm0723.sn02top E/PRETTY_LOGGER: │ 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
2019-07-22 17:27:13.189 11973-11973/com.gm0723.sn02top E/PRETTY_LOGGER: │ 	at java.lang.Thread.run(Thread.java:762)

**Comment by poptong** [comment]
It seems to be a problem with outdated ffmpeg.
Is this possible to solve?

https://github.com/ytdl-org/youtube-dl/issues/20095#issue-415916121
