### ISSUE TITLE
Failure to get stream from URL

### ISSUE THREAD

**Issue by hyoromo** [yausername/youtubedl-android#215]
Video playback has failed since today.
The following error also occurs in the debug apk of v0.14.0.

```
E/StreamingExample: failed to get stream info
    com.yausername.youtubedl_android.YoutubeDLException: WARNING: "-f best" selects the best pre-merged format which is often not the best option.
             To let yt-dlp download and merge the best available formats, simply do not pass any format selection.
             If you know what you are doing and want only the best pre-merged format, use "-f b" instead to suppress this warning
    WARNING: [youtube] AIcx_mxms5M: nsig extraction failed: You may experience throttling for some formats
             Install PhantomJS to workaround the issue. Please download it from https://phantomjs.org/download.html
             n = d_Jh1vhlJOmKOppL ; player = https://www.youtube.com/s/player/11e3a4ec/player_ias.vflset/en_US/base.js
    ERROR: [youtube] AIcx_mxms5M: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
    
        at com.yausername.youtubedl_android.YoutubeDL.execute(YoutubeDL.java:259)
        at com.yausername.youtubedl_android.YoutubeDL.getInfo(YoutubeDL.java:144)
        at com.yausername.youtubedl_android_example.StreamingExampleActivity.lambda$startStream$0(StreamingExampleActivity.java:91)
        at com.yausername.youtubedl_android_example.-$$Lambda$StreamingExampleActivity$FscSQefRSxxaMXoNqDwnr8-PLnU.call(Unknown Source:2)
        at io.reactivex.internal.operators.observable.ObservableFromCallable.subscribeActual(ObservableFromCallable.java:42)
        at io.reactivex.Observable.subscribe(Observable.java:12030)
        at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:579)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
```

**Comment by kyrellous** [comment]
same issue with me

**Comment by JunkFood02** [comment]
update yt-dlp to 2023.02.17
