### ISSUE TITLE
Unable to download webpage [Error]

### ISSUE THREAD

**Issue by RenFinkle** [yausername/youtubedl-android#22]
Initialization Code (runs without throwing error):
```
        try {
            YoutubeDL.getInstance().init(getApplication());
        } catch (YoutubeDLException e) {
            Log.e("Tag", "failed to initialize youtubedl-android", e);
        }
```
Code:
```
        VideoInfo streamInfo;
        try {
            streamInfo = YoutubeDL.getInstance().getInfo("https://vimeo.com/22439234");
            value = streamInfo.getTitle();
        } catch (YoutubeDLException e) {
            value = "Error";
            Log.e("Tag", "Error", e);
        }
```
Error:
```
2019-08-12 12:59:15.977 22202-22202/com.base.y23 E/Tag: Error
    com.yausername.youtubedl_android.YoutubeDLException: ERROR: Unable to download webpage: <urlopen error [Errno 7] No address associated with hostname> (caused by URLError(gaierror(7, 'No address associated with hostname')))
    
        at com.yausername.youtubedl_android.YoutubeDL.execute(YoutubeDL.java:178)
        at com.yausername.youtubedl_android.YoutubeDL.getInfo(YoutubeDL.java:116)
        at com.base.y23.MainActivity.sendMessage(MainActivity.java:101)
        at java.lang.reflect.Method.invoke(Native Method)
        at androidx.appcompat.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:385)
        at android.view.View.performClick(View.java:6597)
        at android.view.View.performClickInternal(View.java:6574)
        at android.view.View.access$3100(View.java:778)
        at android.view.View$PerformClick.run(View.java:25885)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```
Phone used for debugging: Pixel 3XL
Android version: 9
And in case it helps here's my app gradle:
```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 29
    buildToolsVersion "29.0.2"
    defaultConfig {
        applicationId "com.base.y23"
        minSdkVersion 17
        targetSdkVersion 29
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.appcompat:appcompat:1.0.2'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    implementation 'com.google.android.material:material:1.0.0'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.2.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
    implementation 'androidx.recyclerview:recyclerview:1.0.0'
    implementation 'com.github.yausername.youtubedl-android:library:0.6.+'
    implementation 'com.github.yausername.youtubedl-android:ffmpeg:0.6.+'
}
```
Any help would be greatly appreciated.

**Comment by RenFinkle** [comment]
`YoutubeDL.getInstance().updateYoutubeDL(getApplication());` seems to fix this, closed.
