### ISSUE TITLE
Download Errors:  File "<frozen importlib._bootstrap>"

### ISSUE THREAD

**Issue by deniscerri** [yausername/youtubedl-android#242]
Hello there. I am the developer of ytdlnis, an app using your library. 
I am using the commit "23b26d55f838626bc63e2b4964d97062a5e46e50" almost everyone has no issues with it but a few

Some of them are getting some random python errors. I hope you take a look at this and see if there is a problem somewhere. 
Thanks for building this lib.

`Traceback (most recent call last):
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/yt-dlp/yt-dlp/__main__.py", line 14, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/__init__.py", line 19, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/cookies.py", line 21, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/aes.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/data/user/0/com.deniscerri.ytdl/no_b`
  
  The configuration that the user used:
  -N 9 --no-mtime --sponsorblock-remove "sponsor,music_offtopic" --restrict-filenames --sponsorblock-mark all --embed-chapters --embed-subs --sub-langs all -f "247+bestaudio/best/247"

**Comment by JunkFood02** [comment]
the log seems truncated?

**Comment by deniscerri** [comment]
`Traceback (most recent call last):
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/yt-dlp/yt-dlp/main.py", line 14, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/init.py", line 19, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/cookies.py", line 21, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/aes.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/dependencies/init.py", line 69, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/dependencies/Cryptodome.py", line 19, in <module>
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/site-packages/Cryptodome/Cipher/init.py", line 28, in <module>
    from Cryptodome.Cipher._mode_cbc import _create_cbc_cipher
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/site-packages/Cryptodome/Cipher/_mode_cbc.py", line 45, in <module>
    raw_cbc_lib = load_pycryptodome_raw_lib("Cryptodome.Cipher._raw_cbc", """
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/site-packages/Cryptodome/Util/_raw_api.py", line 309, in load_pycryptodome_raw_lib
    raise OSError("Cannot load native module '%s': %s" % (name, ", ".join(attempts)))
OSError: Cannot load native module 'Cryptodome.Cipher._raw_cbc': Not found '[_raw_cbc.cpython-38.so](http://_raw_cbc.cpython-38.so/)', Cannot load '[_raw_cbc.abi3.so](http://_raw_cbc.abi3.so/)': dlopen failed: cannot locate symbol "__aeabi_memcpy4" referenced by "/data/data/com.deniscerri.ytdl/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/site-packages/Cryptodome/Cipher/_raw_cbc.abi3.so"..., Not found '_raw_cbc.so'`

@JunkFood02 It appears to be a cryptomedex error.
The device is running android 6.0.1

**Comment by zaednasr** [comment]
any updates on this?
