### ISSUE TITLE
files/youtubedl-android/packages/usr/bin/python: No such file or directory

### ISSUE THREAD

**Issue by WtfJoke** [yausername/youtubedl-android#25]
Hi @yausername thanks for your work here :)

I followed the readme on a new app but each time I try to interact with YoutubeDL I get following exception:

Do I need to bundle python with it? Or do you know what im doing wrong?

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: me.wessner.youtubedl, PID: 4430
    java.lang.IllegalStateException: Could not execute method for android:onClick
        at androidx.appcompat.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:390)
        at android.view.View.performClick(View.java:5610)
        at android.view.View$PerformClick.run(View.java:22265)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6077)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at androidx.appcompat.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:385)
        at android.view.View.performClick(View.java:5610) 
        at android.view.View$PerformClick.run(View.java:22265) 
        at android.os.Handler.handleCallback(Handler.java:751) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6077) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756) 
     Caused by: com.yausername.youtubedl_android.YoutubeDLException: java.io.IOException: Cannot run program "/data/user/0/me.wessner.youtubedl/files/youtubedl-android/packages/usr/bin/python": error=2, No such file or directory
        at com.yausername.youtubedl_android.YoutubeDL.execute(YoutubeDL.java:157)
        at com.yausername.youtubedl_android.YoutubeDL.getInfo(YoutubeDL.java:116)
        at me.wessner.youtubedl.MainActivity.onClickDownload(MainActivity.kt:44)
        at java.lang.reflect.Method.invoke(Native Method) 
        at androidx.appcompat.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:385) 
        at android.view.View.performClick(View.java:5610) 
        at android.view.View$PerformClick.run(View.java:22265) 
        at android.os.Handler.handleCallback(Handler.java:751) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6077) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756) 
     Caused by: java.io.IOException: Cannot run program "/data/user/0/me.wessner.youtubedl/files/youtubedl-android/packages/usr/bin/python": error=2, No such file or directory
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:983)
        at com.yausername.youtubedl_android.YoutubeDL.execute(YoutubeDL.java:155)
        at com.yausername.youtubedl_android.YoutubeDL.getInfo(YoutubeDL.java:116) 
        at me.wessner.youtubedl.MainActivity.onClickDownload(MainActivity.kt:44) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at androidx.appcompat.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:385) 
        at android.view.View.performClick(View.java:5610) 
        at android.view.View$PerformClick.run(View.java:22265) 
        at android.os.Handler.handleCallback(Handler.java:751) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6077) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756) 
     Caused by: java.io.IOException: error=2, No such file or directory
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:133)
        at java.lang.ProcessImpl.start(ProcessImpl.java:128)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:964)
        at com.yausername.youtubedl_android.YoutubeDL.execute(YoutubeDL.java:155) 
        at com.yausername.youtubedl_android.YoutubeDL.getInfo(YoutubeDL.java:116) 
        at me.wessner.youtubedl.MainActivity.onClickDownload(MainActivity.kt:44) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at androidx.appcompat.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:385) 
        at android.view.View.performClick(View.java:5610) 
        at android.view.View$PerformClick.run(View.java:22265) 
        at android.os.Handler.handleCallback(Handler.java:751) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6077) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756) 

```

**Comment by yausername** [comment]
Hi @WtfJoke 



> Do I need to bundle python with it?

No. It is already bundled.

Here are few questions/suggestions.

- Can you try to force stop, clear data and restart app?
- What android version & device are you using?
- Can you provide the code for how you are initializing and using the library?

Thanks

**Comment by WtfJoke** [comment]
Hi @yausername 

>     Can you try to force stop, clear data and restart app?
I havent tried that yet, but yesterday I debugged the library code and uninstalled/reinstalled the app couple times. Python and YoutubeDL get initialized correctly (I think). It crashes on this [line ](https://github.com/yausername/youtubedl-android/blob/master/library/src/main/java/com/yausername/youtubedl_android/YoutubeDL.java#L155) (but can be seen on stacktrace as well). However pythonPath.exists() returns true. 

>     What android version & device are you using?

I use nexus 4 emulator. I think it has jelly bean. Will get back to you this evening probably.

>     Can you provide the code for how you are initializing and using the library?

Here is the code I used: https://github.com/WtfJoke/youtubedl


I will write more details this evening most likely

**Comment by bunaif** [comment]
@WtfJoke @yausername   when i test in android kitkat not working also tested on android 5 give me this error 
![Screenshot_٢٠١٩١٠٢٢-١٢٢٩٠١_Gallery](https://user-images.githubusercontent.com/20098154/67269310-8d6e5c00-f4c7-11e9-8996-d12ecb24106d.jpg)

**Comment by yausername** [comment]
> I use nexus 4 emulator. I think it has jelly bean

Termux packages support only android 5.0 and later as discussed [here](https://github.com/termux/termux-app/issues/6). I think I should change the `minSdkVersion` appropriately.
You can try with arm image of a recent android version on the emulator.

**Comment by WtfJoke** [comment]
I should have mentioned that your sample app works without any problems on the very same emulator. 
I will try on a more recent android version as well

**Comment by yausername** [comment]
Try this first - on the same emulator force stop, clear data and reopen app and see what happens.

**Comment by WtfJoke** [comment]
Allright, took a little bit longer than expected.
Its a Nexus 4 Emulator, API 24 (Target Android 7.0), x86.

After I force stopped, clear data and reopen the app it caused:

[stacktrace.txt](https://github.com/yausername/youtubedl-android/files/3769463/stacktrace.txt)

After reopening it again, the same error is caused as in the issue description.

And I can also confirm that on my real phone (Android 9) everything works.

**Comment by yausername** [comment]
Hi, sorry for the late reply.
It might be happening due to the x86 emulator. Select an arm image instead
of x86 when creating emulator as explained here -
https://stackoverflow.com/questions/30405740/android-studio-how-can-i-make-an-avd-with-arm-instead-of-haxm/46677457#46677457

**Comment by WtfJoke** [comment]
Allright, thanks for pointing out. I will use my real device for testing. The ARM Images are super slow (10min+ to even boot). 

Thank you for your continued and fast support, appreciate that 👍
