### ISSUE TITLE
facebook video not working 

### ISSUE THREAD

**Issue by MohitDer** [yausername/youtubedl-android#269]
W  com.yausername.youtubedl_android.YoutubeDLException: ERROR: [facebook] 708611673740596: Cannot parse data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
2024-04-06 18:07:12.853 11292-11292 System.err              com.app.fbdownloader                 W  	at com.yausername.youtubedl_android.YoutubeDL.execute(YoutubeDL.kt:202)
2024-04-06 18:07:12.853 11292-11292 System.err              com.app.fbdownloader                 W  	at com.yausername.youtubedl_android.YoutubeDL.getInfo(YoutubeDL.kt:108)
2024-04-06 18:07:12.853 11292-11292 System.err              com.app.fbdownloader                 W  	at com.yausername.youtubedl_android.YoutubeDL.getInfo(YoutubeDL.kt:102)
2024-04-06 18:07:12.853 11292-11292 System.err              com.app.fbdownloader                 W  	at com.app.fbdownloader.fragment.URLDownloadFragment.getFacebookData(URLDownloadFragment.java:188)
2024-04-06 18:07:12.853 11292-11292 System.err              com.app.fbdownloader                 W  	at com.app.fbdownloader.fragment.URLDownloadFragment.lambda$initViews$1$URLDownloadFragment(URLDownloadFragment.java:170)
2024-04-06 18:07:12.853 11292-11292 System.err              com.app.fbdownloader                 W  	at com.app.fbdownloader.fragment.-$$Lambda$URLDownloadFragment$2lkqSME2VfFCBDcOzDa8Mmm5MIw.onClick(Unknown Source:2)
2024-04-06 18:07:12.853 11292-11292 System.err              com.app.fbdownloader                 W  	at android.view.View.performClick(View.java:6605)
2024-04-06 18:07:12.853 11292-11292 System.err              com.app.fbdownloader                 W  	at android.view.View.performClickInternal(View.java:6582)
2024-04-06 18:07:12.853 11292-11292 System.err              com.app.fbdownloader                 W  	at android.view.View.access$3100(View.java:778)
2024-04-06 18:07:12.853 11292-11292 System.err              com.app.fbdownloader                 W  	at android.view.View$PerformClick.run(View.java:25897)
2024-04-06 18:07:12.854 11292-11292 System.err              com.app.fbdownloader                 W  	at android.os.Handler.handleCallback(Handler.java:873)
2024-04-06 18:07:12.854 11292-11292 System.err              com.app.fbdownloader                 W  	at android.os.Handler.dispatchMessage(Handler.java:99)
2024-04-06 18:07:12.854 11292-11292 System.err              com.app.fbdownloader                 W  	at android.os.Looper.loop(Looper.java:193)
2024-04-06 18:07:12.854 11292-11292 System.err              com.app.fbdownloader                 W  	at android.app.ActivityThread.main(ActivityThread.java:6762)
2024-04-06 18:07:12.854 11292-11292 System.err              com.app.fbdownloader                 W  	at java.lang.reflect.Method.invoke(Native Method)
2024-04-06 18:07:12.854 11292-11292 System.err              com.app.fbdownloader                 W  	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
2024-04-06 18:07:12.854 11292-11292 System.err              com.app.fbdownloader                 W  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by thanhnamzzz** [comment]
You must update this library's channel to fix the 'Cannot parse data' error. I recently encountered this error and managed to fix it.

You can call the updateYoutubeDL() function in the onCreate method of the activity or splash activity, before executing the main functions of this library.

private val compositeDisposable = CompositeDisposable()
private fun updateYoutubeDL() {
        binding.loading.visibility()
        val disposable = Observable.fromCallable { YoutubeDL.getInstance().updateYoutubeDL(this, YoutubeDL.UpdateChannel._STABLE) }
            .subscribeOn(Schedulers.newThread())
            .observeOn(AndroidSchedulers.mainThread())
            .subscribe({ status: UpdateStatus? ->
                binding.loading.gone()
                when (status) {
                    UpdateStatus.DONE -> {
                        Toast.makeText(this@DownloadActivity, "Update successful", Toast.LENGTH_SHORT).show()
                    }

                    UpdateStatus.ALREADY_UP_TO_DATE -> { 
                        Toast.makeText(this@DownloadActivity, "Already up to date", Toast.LENGTH_SHORT).show()
                    }

                    else -> {
                        Toast.makeText(this@DownloadActivity, "$status", Toast.LENGTH_SHORT).show()
                    }
                }
            }, { e: Throwable? ->
                if (BuildConfig.DEBUG) Log.e("Namzzz", "DownloadActivity: failed to update", e)
                binding.loading.gone()
                Toast.makeText(this@DownloadActivity, "Update failed", Toast.LENGTH_SHORT).show()
            })
        compositeDisposable.add(disposable)
    }
