### ISSUE TITLE
ffmpeg is not installed

### ISSUE THREAD

**Issue by Dart2112** [yausername/youtubedl-android#292]
I have initialized and can use yt-dlp successfully but it doesn't seem to detect FFmpeg.
Here is my code in onCreate
![image](https://github.com/user-attachments/assets/329a5035-f1a8-433a-8ede-f5712b64cf19)
This is the first app I've developed so I am probably making a simple mistake but I can't work it out
Here is the execution part of the code
![image](https://github.com/user-attachments/assets/84ed133f-2ec8-4fd4-83df-281d3593a8d0)
It all works if it can download just a mp4, but if I try and download a video from Reddit where it needs to merge formats I get this error
`WARNING: You have requested merging of multiple formats but ffmpeg is not installed. The formats won't be merged
2024`
Is there another step to setting up FFmpeg that I need to do?

**Comment by coffeegrind123** [comment]
Having similiar problems here. Running ffmpeg with -vU produces this:

```
                                                                                                    [debug] Invoking ffmpeg downloader on "https://something.com/myfile.m3u8"
                                                                                                    ERROR: m3u8 download detected but ffmpeg could not be found. Please install
                                                                                                      File "/data/user/0/com.example.myapplication/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/runpy.py", line 192, in _run_module_as_main
                                                                                                        return _run_code(code, main_globals, None,
                                                                                                      File "/data/user/0/com.example.myapplication/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/runpy.py", line 85, in _run_code
                                                                                                        exec(code, run_globals)
                                                                                                      File "/data/user/0/com.example.myapplication/no_backup/youtubedl-android/yt-dlp/yt-dlp/__main__.py", line 17, in <module>
                                                                                                        yt_dlp.main()
                                                                                                      File "/data/user/0/com.example.myapplication/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/__init__.py", line 1081, in main
                                                                                                        _exit(*variadic(_real_main(argv)))
                                                                                                      File "/data/user/0/com.example.myapplication/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/__init__.py", line 1071, in _real_main
                                                                                                        return ydl.download(all_urls)
                                                                                                      File "/data/user/0/com.example.myapplication/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 3607, in download
                                                                                                        self.__download_wrapper(self.extract_info)(
                                                                                                      File "/data/user/0/com.example.myapplication/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 3582, in wrapper
                                                                                                        res = func(*args, **kwargs)
                                                                                                      File "/data/user/0/com.example.myapplication/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 1615, in extract_info
                                                                                                        return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
                                                                                                      File "/data/user/0/com.example.myapplication/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 1626, in wrapper
                                                                                                        return func(self, *args, **kwargs)
                                                                                                      File "/data/user/0/com.example.myapplication/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 1782, in __extract_info
                                                                                                        return self.process_ie_result(ie_result, download, extra_info)
                                                                                                      File "/data/user/0/com.example.myapplication/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 1841, in process_ie_result
                                                                                                        ie_result = self.process_video_result(ie_result, download=download)
                                                                                                      File "/data/user/0/com.example.myapplication/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 3015, in process_video_result
                                                                                                        self.process_info(new_info)
2024-08-17 18:32:31.889 12730-12842 YoutubeDLException      com.example.myapplication            E    File "/data/user/0/com.example.myapplication/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 179, in wrapper
                                                                                                        return func(self, *args, **kwargs)
                                                                                                      File "/data/user/0/com.example.myapplication/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 3483, in process_info
                                                                                                        success, real_download = self.dl(temp_filename, info_dict)
                                                                                                      File "/data/user/0/com.example.myapplication/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 3203, in dl
                                                                                                        return fd.download(name, new_info, subtitle)
                                                                                                      File "/data/user/0/com.example.myapplication/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/downloader/common.py", line 466, in download
                                                                                                        ret = self.real_download(filename, info_dict)
                                                                                                      File "/data/user/0/com.example.myapplication/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/downloader/external.py", line 50, in real_download
                                                                                                        retval = self._call_downloader(tmpfilename, info_dict)
                                                                                                      File "/data/user/0/com.example.myapplication/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/downloader/external.py", line 481, in _call_downloader
                                                                                                        self.report_error('m3u8 download detected but ffmpeg could not be found. Please install')
                                                                                                      File "/data/user/0/com.example.myapplication/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 1092, in report_error
                                                                                                        self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
                                                                                                      File "/data/user/0/com.example.myapplication/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 1020, in trouble
                                                                                                        tb_data = traceback.format_list(traceback.extract_stack())
                                                                                                    
                                                                                                    ERROR: Unable to download video: [Errno 2] No such file or directory: '/storage/emulated/0/Download/youtubedl-android/JUX-211.mp4.part'
                                                                                                    Traceback (most recent call last):
                                                                                                      File "/data/user/0/com.example.myapplication/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 3483, in process_info
                                                                                                        success, real_download = self.dl(temp_filename, info_dict)
                                                                                                      File "/data/user/0/com.example.myapplication/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 3203, in dl
                                                                                                        return fd.download(name, new_info, subtitle)
                                                                                                      File "/data/user/0/com.example.myapplication/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/downloader/common.py", line 466, in download
                                                                                                        ret = self.real_download(filename, info_dict)
                                                                                                      File "/data/user/0/com.example.myapplication/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/downloader/external.py", line 70, in real_download
                                                                                                        fsize = os.path.getsize(encodeFilename(tmpfilename))
                                                                                                      File "/data/user/0/com.example.myapplication/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/genericpath.py", line 50, in getsize
                                                                                                        return os.stat(filename).st_size
                                                                                                    FileNotFoundError: [Errno 2] No such file or directory: '/storage/emulated/0/Download/youtubedl-android/JUX-211.mp4.part'
                                                                                                    
                                                                                                    During handling of the above exception, another exception occurred:
                                                                                                    
                                                                                                    Traceback (most recent call last):
                                                                                                      File "/data/user/0/com.example.myapplication/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 1626, in wrapper
                                                                                                        return func(self, *args, **kwargs)
                                                                                                      File "/data/user/0/com.example.myapplication/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 1782, in __extract_info
                                                                                                        return self.process_ie_result(ie_result, download, extra_info)
                                                                                                      File "/data/user/0/com.example.myapplication/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 1841, in process_ie_result
                                                                                                        ie_result = self.process_video_result(ie_result, download=download)
                                                                                                      File "/data/user/0/com.example.myapplication/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 3015, in process_video_result
                                                                                                        self.process_info(new_info)
                                                                                                      File "/data/user/0/com.example.myapplication/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 179, in wrapper
                                                                                                        return func(self, *args, **kwargs)
2024-08-17 18:32:31.889 12730-12842 YoutubeDLException      com.example.myapplication            E    File "/data/user/0/com.example.myapplication/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 3495, in process_info
                                                                                                        raise UnavailableVideoError(err)
                                                                                                    yt_dlp.utils.UnavailableVideoError: Unable to download video: [Errno 2] No such file or directory: '/storage/emulated/0/Download/youtubedl-android/JUX-211.mp4.part'
2024-08-17 18:32:32.300 12730-12997 DownloadOutput          com.example.myapplication            D  
2024-08-17 18:32:32.301 12730-12997 DownloadOutput          com.example.myapplication            D  [download]   0.0% of ~ 951.53MiB at    777.10B/s ETA Unknown (frag 0/1416)
```

**Comment by LunevNF** [comment]
Any ideas?

**Comment by imagination24** [comment]
Hi, I have the same problem, do you have any solution?

**Comment by Dart2112** [comment]
> Hi, I have the same problem, do you have any solution?

Unfortunately not. My primary use case doesn't need FFMPEG so I am still using the library as is. But it would be nice to get it working at some point.

**Comment by alexch33** [comment]
Same problem, i was try to use `ffmpeg-location` option, but didn't succeed, youtube-dlp with new python version just don't see ffmpeg

**Comment by JunkFood02** [comment]
#303

**Comment by alexch33** [comment]
> #303

Thank you, it helped!

**Comment by LunevNF** [comment]
0.17.2:

	Latest version: stable@2024.12.13 from yt-dlp/yt-dlp
	yt-dlp is up to date (stable@2024.12.13 from yt-dlp/yt-dlp)
	[youtube] Extracting URL: https://music.youtube.com/watch?v=lPocTNKY_O0
	[youtube] lPocTNKY_O0: Downloading webpage
	[youtube] lPocTNKY_O0: Downloading ios player API JSON
	[youtube] lPocTNKY_O0: Downloading mweb player API JSON
	[youtube] lPocTNKY_O0: Downloading web music client config
	[youtube] lPocTNKY_O0: Downloading player f8f53e1a
	[youtube] lPocTNKY_O0: Downloading web music player API JSON
	[youtube] lPocTNKY_O0: Downloading m3u8 information
	[info] lPocTNKY_O0: Downloading 1 format(s): 251
	[download] Destination: /storage/emulated/0/Download/yt_music-1734202362610.webm

	[download]   0.0% of    3.06MiB at    5.87KiB/s ETA 08:53
	[download]   0.1% of    3.06MiB at   17.45KiB/s ETA 02:59
	[download]   0.2% of    3.06MiB at   40.34KiB/s ETA 01:17
	[download]   0.5% of    3.06MiB at   86.15KiB/s ETA 00:36
	[download]   1.0% of    3.06MiB at  177.48KiB/s ETA 00:17
	[download]   2.0% of    3.06MiB at  221.90KiB/s ETA 00:13
	[download]   4.1% of    3.06MiB at  281.81KiB/s ETA 00:10
	[download]   8.1% of    3.06MiB at  340.42KiB/s ETA 00:08
	[download]  16.3% of    3.06MiB at  512.95KiB/s ETA 00:05
	[download]  32.6% of    3.06MiB at  615.89KiB/s ETA 00:03
	[download]  57.2% of    3.06MiB at  717.84KiB/s ETA 00:01
	[download]  86.5% of    3.06MiB at  701.14KiB/s ETA 00:00
	[download] 100.0% of    3.06MiB at  743.78KiB/s ETA 00:00
	[download] 100% of    3.06MiB in 00:00:04 at 666.56KiB/s 
	ERROR: Postprocessing: ffprobe and ffmpeg not found. Please install or provide the path using --ffmpeg-location
