### ISSUE TITLE
issue with facebook urls

### ISSUE THREAD

**Issue by zohaib1313** [yausername/youtubedl-android#30]
2020-01-05 01:06:30.171 26575-26575/com.example.androiddownloader D/youtube: dl initiated
2020-01-05 01:07:19.157 26575-26575/com.example.androiddownloader D/youtube::: https://www.facebook.com/100008731352875/posts/2215335545434136/
2020-01-05 01:07:23.597 26575-28630/com.example.androiddownloader D/youtueb: [debug] System config: []
    [debug] User config: []
    [debug] Custom config: []
    [debug] Command-line args: ['-o', '/storage/emulated/0/Download/youtubedl-android/%(title)s.%(ext)s', '--no-continue', '-4', '--verbose', 'https://www.facebook.com/100008731352875/posts/2215335545434136/']
    [debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
    [debug] youtube-dl version 2019.09.28
    [debug] Lazy loading extractors enabled
    [debug] Python version 3.7.2 (CPython) - Linux-3.10.61-11350514-armv8l-with-libc
    [debug] exe versions: none
    [debug] Proxy map: {}
    ERROR: Unable to extract video ids; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
    Traceback (most recent call last):
      File "/data/data/com.example.androiddownloader/files/youtubedl-android/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
        ie_result = ie.extract(url)
      File "/data/data/com.example.androiddownloader/files/youtubedl-android/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
        ie_result = self._real_extract(url)
      File "/data/data/com.example.androiddownloader/files/youtubedl-android/youtube-dl/youtube_dl/extractor/facebook.py", line 464, in _real_extract
        webpage, 'video ids', group='ids'),
      File "/data/data/com.example.androiddownloader/files/youtubedl-android/youtube-dl/youtube_dl/extractor/common.py", line 1005, in _search_regex
        raise RegexNotFoundError('Unable to extract %s' % _name)
    youtube_dl.utils.RegexNotFoundError: Unable to extract video ids; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
2020-01-05 01:07:23.597 26575-28630/com.example.androiddownloader W/System.err: com.yausername.youtubedl_android.YoutubeDLException: [debug] System config: []
2020-01-05 01:07:23.597 26575-28630/com.example.androiddownloader W/System.err: [debug] Command-line args: ['-o', '/storage/emulated/0/Download/youtubedl-android/%(title)s.%(ext)s', '--no-continue', '-4', '--verbose', 'https://www.facebook.com/100008731352875/posts/2215335545434136/']
2020-01-05 01:07:23.597 26575-28630/com.example.androiddownloader W/System.err: [debug] youtube-dl version 2019.09.28
2020-01-05 01:07:23.597 26575-28630/com.example.androiddownloader W/System.err: ERROR: Unable to extract video ids; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
2020-01-05 01:07:23.597 26575-28630/com.example.androiddownloader W/System.err:   File "/data/data/com.example.androiddownloader/files/youtubedl-android/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
2020-01-05 01:07:23.597 26575-28630/com.example.androiddownloader W/System.err:   File "/data/data/com.example.androiddownloader/files/youtubedl-android/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
2020-01-05 01:07:23.597 26575-28630/com.example.androiddownloader W/System.err:   File "/data/data/com.example.androiddownloader/files/youtubedl-android/youtube-dl/youtube_dl/extractor/facebook.py", line 464, in _real_extract
2020-01-05 01:07:23.597 26575-28630/com.example.androiddownloader W/System.err:   File "/data/data/com.example.androiddownloader/files/youtubedl-android/youtube-dl/youtube_dl/extractor/common.py", line 1005, in _search_regex
2020-01-05 01:07:23.597 26575-28630/com.example.androiddownloader W/System.err: youtube_dl.utils.RegexNotFoundError: Unable to extract video ids; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
2020-01-05 01:07:23.600 26575-28630/com.example.androiddownloader W/System.err:     at com.yausername.youtubedl_android.YoutubeDL.execute(YoutubeDL.java:179)

**Comment by zohaib1313** [comment]
update the dl version too plz

**Comment by bunaif** [comment]
@zohaib1313  There is no video in the link.

![Screenshot_٢٠٢٠٠١٠٥-٠٠٤٣٢٤_Edge](https://user-images.githubusercontent.com/20098154/71771486-0ae92a80-2f55-11ea-81a9-4c6339a52b3c.jpg)

Also, you can update to the latest version from within the app.

last version is 2020.01.01
