### ISSUE TITLE
Error after progaurd apply

### ISSUE THREAD

**Issue by farimarwat** [yausername/youtubedl-android#33]
java.lang.NoSuchFieldError
        at libcore.reflect.AnnotationAccess.decodeValue(AnnotationAccess.java:688)
        at libcore.reflect.AnnotationAccess.getDefaultValue(AnnotationAccess.java:361)
        at java.lang.reflect.Method.getDefaultValue(Method.java:327)
        at libcore.reflect.AnnotationFactory.getElementsDescription(AnnotationFactory.java:75)
        at libcore.reflect.AnnotationFactory.<init>(AnnotationFactory.java:112)
        at libcore.reflect.AnnotationFactory.createAnnotation(AnnotationFactory.java:94)
        at libcore.reflect.AnnotationAccess.toAnnotationInstance(AnnotationAccess.java:666)
        at libcore.reflect.AnnotationAccess.annotationSetToAnnotations(AnnotationAccess.java:633)
        at libcore.reflect.AnnotationAccess.getDeclaredAnnotations(AnnotationAccess.java:161)
        at java.lang.reflect.Field.getDeclaredAnnotations(Field.java:244)
        at com.a.a.c.f.g.a(Unknown Source)
        at com.a.a.c.f.g.a(Unknown Source)
        at com.a.a.c.f.g.a(Unknown Source)
        at com.a.a.c.f.b.n(Unknown Source)
        at com.a.a.c.f.b.l(Unknown Source)
        at com.a.a.c.f.z.a(Unknown Source)
        at com.a.a.c.f.z.m(Unknown Source)
        at com.a.a.c.f.z.l(Unknown Source)
        at com.a.a.c.f.z.d(Unknown Source)
        at com.a.a.c.f.p.w(Unknown Source)
        at com.a.a.c.f.p.h(Unknown Source)
        at com.a.a.c.c.b.c(Unknown Source)
        at com.a.a.c.c.b.b(Unknown Source)
        at com.a.a.c.c.b.a(Unknown Source)
        at com.a.a.c.c.f.g(Unknown Source)
        at com.a.a.c.c.f.d(Unknown Source)
        at com.a.a.c.c.n.a(Unknown Source)
        at com.a.a.c.c.n.e(Unknown Source)
        at com.a.a.c.c.n.d(Unknown Source)
        at com.a.a.c.c.n.c(Unknown Source)
        at com.a.a.c.c.n.a(Unknown Source)
        at com.a.a.c.g.b(Unknown Source)
        at com.a.a.c.s.a(Unknown Source)
        at com.a.a.c.s.a(Unknown Source)
        at com.a.a.c.s.a(Unknown Source)
        at com.yausername.youtubedl_android.YoutubeDL.getInfo(Unknown Source)
        at com.******.******mcqs.YoutubeplayerActivity.o(Unknown Source)
        at com.******.******mcqs.YoutubeplayerActivity.onCreate(Unknown Source)
        at android.app.Activity.performCreate(Activity.java:6331)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1113)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2523)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2658)
        at android.app.ActivityThread.-wrap11(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1492)
        at android.os.Handler.dispatchMessage(Handler.java:111)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:5737)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
     Caused by: java.lang.NoSuchFieldException: No field AUTO in class Lcom/a/a/a/u$a; (declaration of 'com.a.a.a.u$a' appears in /data/app/com.******.******-1/base.apk)
        at java.lang.Class.getDeclaredField(Native Method)
        at libcore.reflect.AnnotationAccess.decodeValue(AnnotationAccess.java:685)
        at libcore.reflect.AnnotationAccess.getDefaultValue(AnnotationAccess.java:361) 
        at java.lang.reflect.Method.getDefaultValue(Method.java:327) 
        at libcore.reflect.AnnotationFactory.getElementsDescription(AnnotationFactory.java:75) 
        at libcore.reflect.AnnotationFactory.<init>(AnnotationFactory.java:112) 
        at libcore.reflect.AnnotationFactory.createAnnotation(AnnotationFactory.java:94) 
        at libcore.reflect.AnnotationAccess.toAnnotationInstance(AnnotationAccess.java:666) 
        at libcore.reflect.AnnotationAccess.annotationSetToAnnotations(AnnotationAccess.java:633) 
        at libcore.reflect.AnnotationAccess.getDeclaredAnnotations(AnnotationAccess.java:161) 
        at java.lang.reflect.Field.getDeclaredAnnotations(Field.java:244) 
        at com.a.a.c.f.g.a(Unknown Source) 
        at com.a.a.c.f.g.a(Unknown Source) 
        at com.a.a.c.f.g.a(Unknown Source) 
        at com.a.a.c.f.b.n(Unknown Source) 
        at com.a.a.c.f.b.l(Unknown Source) 
        at com.a.a.c.f.z.a(Unknown Source) 
        at com.a.a.c.f.z.m(Unknown Source) 
        at com.a.a.c.f.z.l(Unknown Source) 
        at com.a.a.c.f.z.d(Unknown Source) 
        at com.a.a.c.f.p.w(Unknown Source) 
        at com.a.a.c.f.p.h(Unknown Source) 
        at com.a.a.c.c.b.c(Unknown Source) 
        at com.a.a.c.c.b.b(Unknown Source) 
        at com.a.a.c.c.b.a(Unknown Source) 
        at com.a.a.c.c.f.g(Unknown Source) 
        at com.a.a.c.c.f.d(Unknown Source) 
        at com.a.a.c.c.n.a(Unknown Source) 
        at com.a.a.c.c.n.e(Unknown Source) 
        at com.a.a.c.c.n.d(Unknown Source) 
        at com.a.a.c.c.n.c(Unknown Source) 
        at com.a.a.c.c.n.a(Unknown Source) 
        at com.a.a.c.g.b(Unknown Source) 
        at com.a.a.c.s.a(Unknown Source) 
        at com.a.a.c.s.a(Unknown Source) 
        at com.a.a.c.s.a(Unknown Source) 
        at com.yausername.youtubedl_android.YoutubeDL.getInfo(Unknown Source) 
        at com.******.******mcqs.YoutubeplayerActivity.o(Unknown Source) 
        at com.******.******mcqs.YoutubeplayerActivity.onCreate(Unknown Source) 
        at android.app.Activity.performCreate(Activity.java:6331) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1113) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2523) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2658) 
        at android.app.ActivityThread.-wrap11(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1492) 
        at android.os.Handler.dispatchMessage(Handler.java:111) 
        at android.os.Looper.loop(Looper.java:207) 
        at android.app.ActivityThread.main(ActivityThread.java:5737) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)

**Comment by farimarwat** [comment]
Updated:
Problem Fixed:
Problem was due to this Line: 
Caused by: java.lang.NoSuchFieldException: No field **_AUTO_**
