### ISSUE TITLE
Apk test request

### ISSUE THREAD

**Issue by yausername** [yausername/youtubedl-android#44]
Hi all,

I have not been able to test the latest release with older android versions.
Please test below apks with android versions 5,6,7 and 8 and share feedback.
I have tested with versions 9 and 10.
[ARM](https://github.com/yausername/files/blob/master/apks/app-armeabi-debug.apk)
[x86](https://github.com/yausername/files/blob/master/apks/app-x86-debug.apk)

Thanks

**Comment by bunaif** [comment]
Hi, I'm testing on android 5.0.2 on device Samsung SM-G530H not working, command failed.

**Comment by yausername** [comment]
It seems like termux only supports android version >=7.0 (https://github.com/termux/termux-packages/commit/a48d94ce2b87fdecd4f7c55b2f5205ce21bdba9c)
This could be the reason why it doesn't work on pre 7.0 devices.

**Comment by yausername** [comment]
I will try with the legacy branch of termux https://github.com/termux/termux-packages/tree/android-5 for which the packages are hosted [here](http://termux.net/dists/stable/main/)

**Comment by bunaif** [comment]
Yes I think so, it is a good idea if you come up with some way for Android 5 and 6.

Thanks for your great work.

**Comment by yausername** [comment]
I have updated the apks above with legacy termux packages which are supposed to work with android 5 and above. Please test and let me know.

**Comment by jungyoungsoo** [comment]
sir i just test now . it work android10 but not work android6 may be api level < 24 not work.
please update. T_T

**Comment by yausername** [comment]
What error do you see? Which android 6 device do you have?
Make sure you uninstall the apk and then install [this](https://github.com/yausername/files/blob/master/apks/app-armeabi-debug.apk) before testing.

**Comment by jungyoungsoo** [comment]
yes i'm sure.  I'm download from https://github.com/yausername/files.git
samesung galaxy s6 edge+ osversion 6.0.1 and galaxy note4 os versiont 6.0.1

**Comment by yausername** [comment]
Ok. Please try [this apk](https://github.com/yausername/files/blob/master/apks/test/app-armeabi-debug.apk). Try to download something, it will print error logs at `Downloads/youtubedl-android/logs.txt`. Share the error logs here.

**Comment by yausername** [comment]
@jungyoungsoo Ignore previous comment. Try [this apk](https://github.com/yausername/files/blob/master/apks/test2/app-armeabi-v7a-debug.apk).
Uninstall previous version before installing this.

**Comment by jungyoungsoo** [comment]
ok sir please wait. the phone I left it at home. if finish work i'll check it and share error log thank you

**Comment by yausername** [comment]
Never mind. I found out that it won't work. I am working on a fix and will share an apk later.

**Comment by jungyoungsoo** [comment]
https://github.com/yausername/files/tree/master/apks/test2
app-armeabi-v7a-debug.apk <-- this apk log..

com.yausername.youtubedl_android.YoutubeDLException: CANNOT LINK EXECUTABLE: library "libandroid-support.so" not found
page record for 0xf766b00c was not found (block_size=16)

	at com.yausername.youtubedl_android.YoutubeDL.execute(YoutubeDL.java:196)
	at com.yausername.youtubedl_android_example.DownloadingExampleActivity.lambda$startDownload$0$DownloadingExampleActivity(DownloadingExampleActivity.java:115)
	at com.yausername.youtubedl_android_example.-$$Lambda$DownloadingExampleActivity$DIqcJ_vtApVhyONpHFiA5nyofXo.call(lambda)
	at io.reactivex.internal.operators.observable.ObservableFromCallable.subscribeActual(ObservableFromCallable.java:42)
	at io.reactivex.Observable.subscribe(Observable.java:12030)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:579)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)
com.yausername.youtubedl_android.YoutubeDLException: CANNOT LINK EXECUTABLE: library "libandroid-support.so" not found
page record for 0xf742500c was not found (block_size=16)

	at com.yausername.youtubedl_android.YoutubeDL.execute(YoutubeDL.java:196)
	at com.yausername.youtubedl_android_example.DownloadingExampleActivity.lambda$startDownload$0$DownloadingExampleActivity(DownloadingExampleActivity.java:115)
	at com.yausername.youtubedl_android_example.-$$Lambda$DownloadingExampleActivity$DIqcJ_vtApVhyONpHFiA5nyofXo.call(lambda)
	at io.reactivex.internal.operators.observable.ObservableFromCallable.subscribeActual(ObservableFromCallable.java:42)
	at io.reactivex.Observable.subscribe(Observable.java:12030)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:579)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)
com.yausername.youtubedl_android.YoutubeDLException: CANNOT LINK EXECUTABLE: library "libandroid-support.so" not found
page record for 0xf701100c was not found (block_size=16)

	at com.yausername.youtubedl_android.YoutubeDL.execute(YoutubeDL.java:196)
	at com.yausername.youtubedl_android_example.DownloadingExampleActivity.lambda$startDownload$0$DownloadingExampleActivity(DownloadingExampleActivity.java:115)
	at com.yausername.youtubedl_android_example.-$$Lambda$DownloadingExampleActivity$DIqcJ_vtApVhyONpHFiA5nyofXo.call(lambda)
	at io.reactivex.internal.operators.observable.ObservableFromCallable.subscribeActual(ObservableFromCallable.java:42)
	at io.reactivex.Observable.subscribe(Observable.java:12030)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:579)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)

**Comment by yausername** [comment]
@bunaif @jungyoungsoo 
Please try [this apk](https://github.com/yausername/files/blob/master/apks/test/app-armeabi-v7a-debug.apk)

**Comment by yausername** [comment]
I think [this apk](https://github.com/yausername/files/blob/master/apks/test/app-armeabi-v7a-debug.apk) should work. I managed to test it using emulator. Please try.

**Comment by jungyoungsoo** [comment]
> I think [this apk](https://github.com/yausername/files/blob/master/apks/test/app-armeabi-v7a-debug.apk) should work. I managed to test it using emulator. Please try.

working great sir... 
when you update this version? 
i already test galaxy s6, and note4 version 6.0.1
it's working good perfect.

**Comment by yausername** [comment]
>  when you update this version?

I have released version `0.9.0`
