### ISSUE TITLE
ERROR: Signature extraction failed

### ISSUE THREAD

**Issue by Flah** [yausername/youtubedl-android#50]
With the setup described and the following class, I am not able to get it running:

`
public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        new Thread(() -> {
            try  {
                YoutubeDL.getInstance().init(getApplication());
                YoutubeDL.getInstance().updateYoutubeDL(getApplication());
            } catch (Exception e) {
                e.printStackTrace();
            }
        }).start();

        // Video url to download
        String videoUrl = "https://www.youtube.com/watch?v=leHXx0QqfJg";

        try {
            YoutubeDL.getInstance().init(getApplication());
        } catch (YoutubeDLException e) {
            Log.e("error", "failed to initialize youtubedl-android", e);
        }

        File youtubeDLDir = new File(Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS), "youtubedl-android");
        YoutubeDLRequest request = new YoutubeDLRequest(videoUrl);
        //request.addOption("--no-check-certificate");
        //request.addOption("-o", youtubeDLDir.getAbsolutePath() + "/%(title)s.%(ext)s");

        try {
            YoutubeDL.getInstance().execute(request);
        } catch (InterruptedException e) {
            e.printStackTrace();
        } catch (YoutubeDLException e) {
            e.printStackTrace();
        }

        /*
        try {
            YoutubeDL.getInstance().execute(request, (progress, etaInSeconds) -> {
                Log.i("print", String.valueOf(progress) + "% (ETA " + String.valueOf(etaInSeconds) + " seconds)");
            });
        } catch (YoutubeDLException e) {
            e.printStackTrace();
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        */
    }
}
`

The following is the error log:
`2020-05-16 16:22:21.962 13015-13047/com.example.myapplication W/libc: Unable to set property "qemu.gles" to "1": connection failed; errno=13 (Permission denied)
2020-05-16 16:22:25.750 13015-13015/com.example.myapplication W/System.err: com.yausername.youtubedl_android.YoutubeDLException: ERROR: Signature extraction failed: Traceback (most recent call last):
2020-05-16 16:22:25.750 13015-13015/com.example.myapplication W/System.err:   File "/data/data/com.example.myapplication/no_backup/youtubedl-android/youtube-dl/youtube_dl/extractor/common.py", line 627, in _request_webpage
2020-05-16 16:22:25.750 13015-13015/com.example.myapplication W/System.err:     return self._downloader.urlopen(url_or_request)
2020-05-16 16:22:25.750 13015-13015/com.example.myapplication W/System.err:   File "/data/data/com.example.myapplication/no_backup/youtubedl-android/youtube-dl/youtube_dl/YoutubeDL.py", line 2238, in urlopen
2020-05-16 16:22:25.751 13015-13015/com.example.myapplication W/System.err:     return self._opener.open(req, timeout=self._socket_timeout)
2020-05-16 16:22:25.751 13015-13015/com.example.myapplication W/System.err:   File "/data/user/0/com.example.myapplication/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/urllib/request.py", line 531, in open
2020-05-16 16:22:25.751 13015-13015/com.example.myapplication W/System.err:     response = meth(req, response)
2020-05-16 16:22:25.751 13015-13015/com.example.myapplication W/System.err:   File "/data/data/com.example.myapplication/no_backup/youtubedl-android/youtube-dl/youtube_dl/utils.py", line 2618, in http_response
2020-05-16 16:22:25.751 13015-13015/com.example.myapplication W/System.err:     content = resp.read()
2020-05-16 16:22:25.751 13015-13015/com.example.myapplication W/System.err:   File "/data/user/0/com.example.myapplication/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/http/client.py", line 467, in read
2020-05-16 16:22:25.751 13015-13015/com.example.myapplication W/System.err:     s = self._safe_read(self.length)
2020-05-16 16:22:25.751 13015-13015/com.example.myapplication W/System.err:   File "/data/user/0/com.example.myapplication/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/http/client.py", line 608, in _safe_read
2020-05-16 16:22:25.751 13015-13015/com.example.myapplication W/System.err:     data = self.fp.read(amt)
2020-05-16 16:22:25.751 13015-13015/com.example.myapplication W/System.err:   File "/data/user/0/com.example.myapplication/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/socket.py", line 669, in readinto
2020-05-16 16:22:25.751 13015-13015/com.example.myapplication W/System.err:     return self._sock.recv_into(b)
2020-05-16 16:22:25.751 13015-13015/com.example.myapplication W/System.err:   File "/data/user/0/com.example.myapplication/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/ssl.py", line 1241, in recv_into
2020-05-16 16:22:25.751 13015-13015/com.example.myapplication W/System.err:     return self.read(nbytes, buffer)
2020-05-16 16:22:25.751 13015-13015/com.example.myapplication W/System.err:   File "/data/user/0/com.example.myapplication/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/ssl.py", line 1099, in read
2020-05-16 16:22:25.751 13015-13015/com.example.myapplication W/System.err:     return self._sslobj.read(len, buffer)
2020-05-16 16:22:25.752 13015-13015/com.example.myapplication W/System.err: ssl.SSLError: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2560)
2020-05-16 16:22:25.752 13015-13015/com.example.myapplication W/System.err: During handling of the above exception, another exception occurred:
2020-05-16 16:22:25.752 13015-13015/com.example.myapplication W/System.err: Traceback (most recent call last):
2020-05-16 16:22:25.752 13015-13015/com.example.myapplication W/System.err:   File "/data/data/com.example.myapplication/no_backup/youtubedl-android/youtube-dl/youtube_dl/extractor/youtube.py", line 1411, in _decrypt_signature
2020-05-16 16:22:25.752 13015-13015/com.example.myapplication W/System.err:     func = self._extract_signature_function(
2020-05-16 16:22:25.752 13015-13015/com.example.myapplication W/System.err:   File "/data/data/com.example.myapplication/no_backup/youtubedl-android/youtube-dl/youtube_dl/extractor/youtube.py", line 1308, in _extract_signature_function
2020-05-16 16:22:25.752 13015-13015/com.example.myapplication W/System.err:     code = self._download_webpage(
2020-05-16 16:22:25.752 13015-13015/com.example.myapplication W/System.err:   File "/data/data/com.example.myapplication/no_backup/youtubedl-android/youtube-dl/youtube_dl/extractor/common.py", line 791, in _download_webpage
2020-05-16 16:22:25.752 13015-13015/com.example.myapplication W/System.err:     res = self._download_webpage_handle(
2020-05-16 16:22:25.752 13015-13015/com.example.myapplication W/System.err:   File "/data/data/com.example.myapplication/no_backup/youtubedl-android/youtube-dl/youtube_dl/extractor/youtube.py", line 271, in _download_webpage_handle
2020-05-16 16:22:25.752 13015-13015/com.example.myapplication W/System.err:     return super(YoutubeBaseInfoExtractor, self)._download_webpage_handle(
2020-05-16 16:22:25.752 13015-13015/com.example.myapplication W/System.err:   File "/data/data/com.example.myapplication/no_backup/youtubedl-android/youtube-dl/youtube_dl/extractor/common.py", line 660, in _download_webpage_handle
2020-05-16 16:22:25.752 13015-13015/com.example.myapplication W/System.err:     urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
2020-05-16 16:22:25.752 13015-13015/com.example.myapplication W/System.err:   File "/data/data/com.example.myapplication/no_backup/youtubedl-android/youtube-dl/youtube_dl/extractor/common.py", line 645, in _request_webpage
2020-05-16 16:22:25.752 13015-13015/com.example.myapplication W/System.err:     raise ExtractorError(errmsg, sys.exc_info()[2], cause=err)
2020-05-16 16:22:25.753 13015-13015/com.example.myapplication W/System.err: youtube_dl.utils.ExtractorError: Download of https://www.youtube.com/s/player/c31ba6fc/player_ias.vflset/en_US/base.js failed: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2560) (caused by SSLError(1, '[SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2560)')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
2020-05-16 16:22:25.753 13015-13015/com.example.myapplication W/System.err:  (caused by ExtractorError("Download of https://www.youtube.com/s/player/c31ba6fc/player_ias.vflset/en_US/base.js failed: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2560) (caused by SSLError(1, '[SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2560)')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.")); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
2020-05-16 16:22:25.755 13015-13015/com.example.myapplication W/System.err:     at com.yausername.youtubedl_android.YoutubeDL.execute(YoutubeDL.java:182)
2020-05-16 16:22:25.756 13015-13015/com.example.myapplication W/System.err:     at com.yausername.youtubedl_android.YoutubeDL.execute(YoutubeDL.java:127)
2020-05-16 16:22:25.756 13015-13015/com.example.myapplication W/System.err:     at com.example.myapplication.MainActivity.onCreate(MainActivity.java:46)
2020-05-16 16:22:25.756 13015-13015/com.example.myapplication W/System.err:     at android.app.Activity.performCreate(Activity.java:7802)
2020-05-16 16:22:25.756 13015-13015/com.example.myapplication W/System.err:     at android.app.Activity.performCreate(Activity.java:7791)
2020-05-16 16:22:25.756 13015-13015/com.example.myapplication W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
2020-05-16 16:22:25.756 13015-13015/com.example.myapplication W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
2020-05-16 16:22:25.756 13015-13015/com.example.myapplication W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
2020-05-16 16:22:25.756 13015-13015/com.example.myapplication W/System.err:     at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
2020-05-16 16:22:25.758 13015-13015/com.example.myapplication W/System.err:     at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
2020-05-16 16:22:25.759 13015-13015/com.example.myapplication W/System.err:     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
2020-05-16 16:22:25.759 13015-13015/com.example.myapplication W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
2020-05-16 16:22:25.759 13015-13015/com.example.myapplication W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:107)
2020-05-16 16:22:25.759 13015-13015/com.example.myapplication W/System.err:     at android.os.Looper.loop(Looper.java:214)
2020-05-16 16:22:25.759 13015-13015/com.example.myapplication W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7356)
2020-05-16 16:22:25.759 13015-13015/com.example.myapplication W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2020-05-16 16:22:25.759 13015-13015/com.example.myapplication W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
2020-05-16 16:22:25.759 13015-13015/com.example.myapplication W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)`

How can this be solved? Thanks in advance!

**Comment by yausername** [comment]
Which version of the library are you using?
This video works for me with the latest version.

**Comment by Flah** [comment]
Thanks for the fast response.
I am using the newest 0.9.0. What else can I post for you to prevent more information?

**Comment by yausername** [comment]
Try with different device.
Try with different video.

**Comment by yausername** [comment]
Closing since this is a youtube-dl issue. Updating will most likely fix it.
