### ISSUE TITLE
does this still work? O am getting this error.

### ISSUE THREAD

**Issue by adetheprince** [yausername/youtubedl-android#55]
E/DownloadingExample: failed to download
    com.yausername.youtubedl_android.YoutubeDLException: ERROR: Signature extraction failed: Traceback (most recent call last):
      File "/data/data/com.yausername.youtubedl_android_example/no_backup/youtubedl-android/youtube-dl/youtube_dl/extractor/common.py", line 627, in _request_webpage
        return self._downloader.urlopen(url_or_request)
      File "/data/data/com.yausername.youtubedl_android_example/no_backup/youtubedl-android/youtube-dl/youtube_dl/YoutubeDL.py", line 2238, in urlopen
        return self._opener.open(req, timeout=self._socket_timeout)
      File "/data/user/0/com.yausername.youtubedl_android_example/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/urllib/request.py", line 531, in open
        response = meth(req, response)
      File "/data/data/com.yausername.youtubedl_android_example/no_backup/youtubedl-android/youtube-dl/youtube_dl/utils.py", line 2624, in http_response
        content = resp.read()
      File "/data/user/0/com.yausername.youtubedl_android_example/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/http/client.py", line 467, in read
        s = self._safe_read(self.length)
      File "/data/user/0/com.yausername.youtubedl_android_example/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/http/client.py", line 610, in _safe_read
        raise IncompleteRead(data, amt-len(data))
    http.client.IncompleteRead: IncompleteRead(437248 bytes read, 367 more expected)
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/data/data/com.yausername.youtubedl_android_example/no_backup/youtubedl-android/youtube-dl/youtube_dl/extractor/youtube.py", line 1419, in _decrypt_signature
        func = self._extract_signature_function(
      File "/data/data/com.yausername.youtubedl_android_example/no_backup/youtubedl-android/youtube-dl/youtube_dl/extractor/youtube.py", line 1316, in _extract_signature_function
        code = self._download_webpage(
      File "/data/data/com.yausername.youtubedl_android_example/no_backup/youtubedl-android/youtube-dl/youtube_dl/extractor/common.py", line 791, in _download_webpage
        res = self._download_webpage_handle(
      File "/data/data/com.yausername.youtubedl_android_example/no_backup/youtubedl-android/youtube-dl/youtube_dl/extractor/youtube.py", line 271, in _download_webpage_handle
        return super(YoutubeBaseInfoExtractor, self)._download_webpage_handle(
      File "/data/data/com.yausername.youtubedl_android_example/no_backup/youtubedl-android/youtube-dl/youtube_dl/extractor/common.py", line 660, in _download_webpage_handle
        urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
      File "/data/data/com.yausername.youtubedl_android_example/no_backup/youtubedl-android/youtube-dl/youtube_dl/extractor/common.py", line 645, in _request_webpage
        raise ExtractorError(errmsg, sys.exc_info()[2], cause=err)
    youtube_dl.utils.ExtractorError: Download of https://www.youtube.com/s/player/39dd62a0/player_ias.vflset/en_US/base.js failed: IncompleteRead(437248 bytes read, 367 more expected) (caused by IncompleteRead(437248 bytes read, 367 more expected)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
E/DownloadingExample:  (caused by ExtractorError('Download of https://www.youtube.com/s/player/39dd62a0/player_ias.vflset/en_US/base.js failed: IncompleteRead(437248 bytes read, 367 more expected) (caused by IncompleteRead(437248 bytes read, 367 more expected)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
    
        at com.yausername.youtubedl_android.YoutubeDL.execute(YoutubeDL.java:182)
        at com.yausername.youtubedl_android_example.DownloadingExampleActivity.lambda$startDownload$0$DownloadingExampleActivity(DownloadingExampleActivity.java:113)
        at com.yausername.youtubedl_android_example.-$$Lambda$DownloadingExampleActivity$DIqcJ_vtApVhyONpHFiA5nyofXo.call(Unknown Source:4)
        at io.reactivex.internal.operators.observable.ObservableFromCallable.subscribeActual(ObservableFromCallable.java:42)
        at io.reactivex.Observable.subscribe(Observable.java:12030)
        at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:579)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
D/EGL_emulation: eglMakeCurrent: 0xddf7fd00: ver 3 0 (tinfo 0xddf2ae80)
D/EGL_emulation: eglMakeCurrent: 0xddf7fd00: ver 3 0 (tinfo 0xddf2ae80)

**Comment by yausername** [comment]
Please update youtube-dl using library provided method.
