### ISSUE TITLE
It's not working with ProGuard

### ISSUE THREAD

**Issue by DexWalker** [yausername/youtubedl-android#71]
Hello.
My app uses obfuscation. However the library does not work.
What do i need to do to make it work?
Obfuscation is very important to me and I would not like to disable it.
Thanks!

**Comment by yausername** [comment]
What is the error you see?

**Comment by DexWalker** [comment]
> What is the error you see?

2020-07-31 10:54:23.315 27366-27786/com.walker.videovk W/System.err: com.yausername.youtubedl_android.YoutubeDLException: ERROR: Signature extraction failed: Traceback (most recent call last):
2020-07-31 10:54:23.315 27366-27786/com.walker.videovk W/System.err:   File "/data/data/com.walker.videovk/no_backup/youtubedl-android/youtube-dl/youtube_dl/extractor/common.py", line 627, in _request_webpage
2020-07-31 10:54:23.315 27366-27786/com.walker.videovk W/System.err:     return self._downloader.urlopen(url_or_request)
2020-07-31 10:54:23.315 27366-27786/com.walker.videovk W/System.err:   File "/data/data/com.walker.videovk/no_backup/youtubedl-android/youtube-dl/youtube_dl/YoutubeDL.py", line 2238, in urlopen
2020-07-31 10:54:23.315 27366-27786/com.walker.videovk W/System.err:     return self._opener.open(req, timeout=self._socket_timeout)
2020-07-31 10:54:23.315 27366-27786/com.walker.videovk W/System.err:   File "/data/user/0/com.walker.videovk/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/urllib/request.py", line 531, in open
2020-07-31 10:54:23.315 27366-27786/com.walker.videovk W/System.err:     response = meth(req, response)
2020-07-31 10:54:23.315 27366-27786/com.walker.videovk W/System.err:   File "/data/data/com.walker.videovk/no_backup/youtubedl-android/youtube-dl/youtube_dl/utils.py", line 2624, in http_response
2020-07-31 10:54:23.315 27366-27786/com.walker.videovk W/System.err:     content = resp.read()
2020-07-31 10:54:23.315 27366-27786/com.walker.videovk W/System.err:   File "/data/user/0/com.walker.videovk/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/http/client.py", line 467, in read
2020-07-31 10:54:23.315 27366-27786/com.walker.videovk W/System.err:     s = self._safe_read(self.length)
2020-07-31 10:54:23.315 27366-27786/com.walker.videovk W/System.err:   File "/data/user/0/com.walker.videovk/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/http/client.py", line 608, in _safe_read
2020-07-31 10:54:23.316 27366-27786/com.walker.videovk W/System.err:     data = self.fp.read(amt)
2020-07-31 10:54:23.316 27366-27786/com.walker.videovk W/System.err:   File "/data/user/0/com.walker.videovk/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/socket.py", line 669, in readinto
2020-07-31 10:54:23.316 27366-27786/com.walker.videovk W/System.err:     return self._sock.recv_into(b)
2020-07-31 10:54:23.316 27366-27786/com.walker.videovk W/System.err:   File "/data/user/0/com.walker.videovk/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/ssl.py", line 1241, in recv_into
2020-07-31 10:54:23.316 27366-27786/com.walker.videovk W/System.err:     return self.read(nbytes, buffer)
2020-07-31 10:54:23.316 27366-27786/com.walker.videovk W/System.err:   File "/data/user/0/com.walker.videovk/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/ssl.py", line 1099, in read
2020-07-31 10:54:23.316 27366-27786/com.walker.videovk W/System.err:     return self._sslobj.read(len, buffer)
2020-07-31 10:54:23.316 27366-27786/com.walker.videovk W/System.err: ssl.SSLError: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2560)
2020-07-31 10:54:23.316 27366-27786/com.walker.videovk W/System.err: During handling of the above exception, another exception occurred:
2020-07-31 10:54:23.316 27366-27786/com.walker.videovk W/System.err: Traceback (most recent call last):
2020-07-31 10:54:23.316 27366-27786/com.walker.videovk W/System.err:   File "/data/data/com.walker.videovk/no_backup/youtubedl-android/youtube-dl/youtube_dl/extractor/youtube.py", line 1425, in _decrypt_signature
2020-07-31 10:54:23.316 27366-27786/com.walker.videovk W/System.err:     func = self._extract_signature_function(
2020-07-31 10:54:23.321 27366-27786/com.walker.videovk W/System.err:   File "/data/data/com.walker.videovk/no_backup/youtubedl-android/youtube-dl/youtube_dl/extractor/youtube.py", line 1322, in _extract_signature_function
2020-07-31 10:54:23.321 27366-27786/com.walker.videovk W/System.err:     code = self._download_webpage(
2020-07-31 10:54:23.321 27366-27786/com.walker.videovk W/System.err:   File "/data/data/com.walker.videovk/no_backup/youtubedl-android/youtube-dl/youtube_dl/extractor/common.py", line 791, in _download_webpage
2020-07-31 10:54:23.321 27366-27786/com.walker.videovk W/System.err:     res = self._download_webpage_handle(
2020-07-31 10:54:23.321 27366-27786/com.walker.videovk W/System.err:   File "/data/data/com.walker.videovk/no_backup/youtubedl-android/youtube-dl/youtube_dl/extractor/youtube.py", line 276, in _download_webpage_handle
2020-07-31 10:54:23.321 27366-27786/com.walker.videovk W/System.err:     return super(YoutubeBaseInfoExtractor, self)._download_webpage_handle(
2020-07-31 10:54:23.321 27366-27786/com.walker.videovk W/System.err:   File "/data/data/com.walker.videovk/no_backup/youtubedl-android/youtube-dl/youtube_dl/extractor/common.py", line 660, in _download_webpage_handle
2020-07-31 10:54:23.321 27366-27786/com.walker.videovk W/System.err:     urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
2020-07-31 10:54:23.321 27366-27786/com.walker.videovk W/System.err:   File "/data/data/com.walker.videovk/no_backup/youtubedl-android/youtube-dl/youtube_dl/extractor/common.py", line 645, in _request_webpage
2020-07-31 10:54:23.322 27366-27786/com.walker.videovk W/System.err:     raise ExtractorError(errmsg, sys.exc_info()[2], cause=err)
2020-07-31 10:54:23.322 27366-27786/com.walker.videovk W/System.err: youtube_dl.utils.ExtractorError: Download of https://www.youtube.com/s/player/c718385a/player_ias.vflset/en_US/base.js failed: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2560) (caused by SSLError(1, '[SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2560)')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
2020-07-31 10:54:23.322 27366-27786/com.walker.videovk W/System.err:  (caused by ExtractorError("Download of https://www.youtube.com/s/player/c718385a/player_ias.vflset/en_US/base.js failed: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2560) (caused by SSLError(1, '[SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2560)')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.")); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
2020-07-31 10:54:23.322 27366-27786/com.walker.videovk W/System.err:     at com.yausername.youtubedl_android.YoutubeDL.b(:196)
2020-07-31 10:54:23.322 27366-27786/com.walker.videovk W/System.err:     at com.yausername.youtubedl_android.YoutubeDL.c(:128)
2020-07-31 10:54:23.323 27366-27786/com.walker.videovk W/System.err:     at com.yausername.youtubedl_android.YoutubeDL.d(:123)
2020-07-31 10:54:23.323 27366-27786/com.walker.videovk W/System.err:     at c.e.a.f1.J(:1296)
2020-07-31 10:54:23.323 27366-27786/com.walker.videovk W/System.err:     at c.e.a.f1.g(:624)
2020-07-31 10:54:23.323 27366-27786/com.walker.videovk W/System.err:     at c.e.a.v0.run(Unknown Source:10)
2020-07-31 10:54:23.324 27366-27786/com.walker.videovk W/System.err:     at java.lang.Thread.run(Thread.java:764)

**Comment by yausername** [comment]
This seems like due to outdated youtube-dl binary.
You can update youtube-dl internally using
```java
YoutubeDL.getInstance().updateYoutubeDL(getApplication());
```

**Comment by DexWalker** [comment]
> This seems like due to outdated youtube-dl binary.
> You can update youtube-dl internally using
> 
> ```java
> YoutubeDL.getInstance().updateYoutubeDL(getApplication());
> ```

No, the library has been updated. My app uses this update function in the "onCreate" method.In addition, everything works perfectly without obfuscation.
Are there other ways, such as what to disable in a file "proguard-rules.pro"?

**Comment by yausername** [comment]
I don't see how obfuscation could cause this error.
You can try to exclude this package by adding these lines to `proguard-rules.pro`
```
#noinspection ShrinkerUnresolvedReference
-keep class com.yausername.** { *; }
```

**Comment by DexWalker** [comment]
> I don't see how obfuscation could cause this error.
> You can try to exclude this package by adding these lines to `proguard-rules.pro`
> 
> ```
> #noinspection ShrinkerUnresolvedReference
> -keep class com.yausername.** { *; }
> ```

Magic!
It works!
Thanks.

**Comment by yausername** [comment]
Seems weird since I  didn't understand what is the cause for the error.
Are you accessing the library via reflection?
Would be interesting to see your proguard config (build.gradle + proguard-rules.pro)  so that I can try to reproduce the issue.
