### ISSUE TITLE
Library Crashes On Open

### ISSUE THREAD

**Issue by UserI33X** [yausername/youtubedl-android#73]
Hi can someone take a look at my code below and tell me why my app crashes on open? Thank you. 

FILE: MainActivity.java

public class MainActivity extends AppCompatActivity {

    private static final String TAG = "MainActivity";

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        try {
            YoutubeDL.getInstance().init(getApplication());
            YoutubeDL.getInstance().updateYoutubeDL(getApplication());
            YoutubeDLRequest request = new YoutubeDLRequest("https://youtu.be/IfJC9vb6p30");
            request.addOption("-f", "best");
            VideoInfo streamInfo = YoutubeDL.getInstance().getInfo(request);
            System.out.println(streamInfo.getUrl());
            TextView tv1 = findViewById(R.id.textView);
            tv1.setText(streamInfo.getUrl());
        } catch (YoutubeDLException | InterruptedException e) {
            Log.e(TAG, "failed to initialize youtubedl-android", e);
        }

    }

}

**Comment by xibr** [comment]
remove this line 
```
YoutubeDL.getInstance().updateYoutubeDL(getApplication());
```

**Comment by yausername** [comment]
What is the error on crash?
Could be due to `NetworkOnMainThreadException`.

**Comment by xibr** [comment]
app crashing if use this line Even if there is an internet connection.

`YoutubeDL.getInstance().updateYoutubeDL(getApplication());`

```
2020-08-13 22:27:20.646 30353-30353/com.example.myapplication E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.myapplication, PID: 30353
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.myapplication/com.example.myapplication.MainActivity}: android.os.NetworkOnMainThreadException
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3632)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3784)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2270)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8125)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
     Caused by: android.os.NetworkOnMainThreadException
        at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1565)
        at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:115)
        at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
        at java.net.InetAddress.getAllByName(InetAddress.java:1152)
        at com.android.okhttp.Dns$1.lookup(Dns.java:41)
        at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:178)
        at com.android.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:144)
        at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:86)
        at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:192)
        at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:144)
        at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:106)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:400)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:333)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:483)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:429)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:252)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:211)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:30)
        at java.net.URL.openStream(URL.java:1072)
        at com.fasterxml.jackson.core.JsonFactory._optimizedStreamFromURL(JsonFactory.java:1595)
        at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:793)
        at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2621)
        at com.yausername.youtubedl_android.YoutubeDLUpdater.checkForUpdate(YoutubeDLUpdater.java:62)
        at com.yausername.youtubedl_android.YoutubeDLUpdater.update(YoutubeDLUpdater.java:29)
        at com.yausername.youtubedl_android.YoutubeDL.updateYoutubeDL(YoutubeDL.java:214)
        at com.example.myapplication.MainActivity.onCreate(MainActivity.java:25)
        at android.app.Activity.performCreate(Activity.java:7957)
        at android.app.Activity.performCreate(Activity.java:7946)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3607)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3784) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2270) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:237) 
        at android.app.ActivityThread.main(ActivityThread.java:8125) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100) 

```

**Comment by yausername** [comment]
Well, that's because making network calls on the main thread is not allowed.
You can see how I use rxJava to do the update on a separate thread [here](https://github.com/yausername/youtubedl-android/blob/master/app/src/main/java/com/yausername/youtubedl_android_example/MainActivity.java#L90).

**Comment by UserI33X** [comment]
public class MainActivity extends AppCompatActivity {

    private boolean updating = false;
    private CompositeDisposable compositeDisposable = new CompositeDisposable();

    private static final String TAG = "MainActivity";

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        try {
            YoutubeDL.getInstance().init(getApplication());
            updateYoutubeDL();


        } catch (YoutubeDLException e) {
            Log.e(TAG, "failed to initialize youtubedl-android", e);
        }


    }
    private void InsertText() throws YoutubeDLException, InterruptedException {
        YoutubeDLRequest request = new YoutubeDLRequest("https://youtu.be/IfJC9vb6p30");
        request.addOption("-f", "best");
        VideoInfo streamInfo = YoutubeDL.getInstance().getInfo(request);
        System.out.println(streamInfo.getUrl());
        TextView tv1 = findViewById(R.id.textView);
        tv1.setText(streamInfo.getUrl());
    }

    @Override
    protected void onDestroy() {
        compositeDisposable.dispose();
        super.onDestroy();
    }

    private void updateYoutubeDL() {
        if (updating) {
            Toast.makeText(MainActivity.this, "update is already in progress", Toast.LENGTH_LONG).show();
            return;
        }

        updating = true;
        Disposable disposable = Observable.fromCallable(() -> YoutubeDL.getInstance().updateYoutubeDL(getApplication()))
                .subscribeOn(Schedulers.newThread())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(status -> {
                    switch (status) {
                        case DONE:
                            Toast.makeText(MainActivity.this, "update successful", Toast.LENGTH_LONG).show();
                            InsertText();
                            break;
                        case ALREADY_UP_TO_DATE:
                            Toast.makeText(MainActivity.this, "already up to date", Toast.LENGTH_LONG).show();
                            InsertText();
                            break;
                        default:
                            Toast.makeText(MainActivity.this, status.toString(), Toast.LENGTH_LONG).show();
                            break;
                    }
                    updating = false;
                }, e -> {
                    if(BuildConfig.DEBUG) Log.e(TAG, "failed to update", e);
                    Toast.makeText(MainActivity.this, "update failed", Toast.LENGTH_LONG).show();
                    updating = false;
                });
        compositeDisposable.add(disposable);
    }


I used your suggestion and copied and pasted the thread but Shouldn't the code above works? Instead it takes me to update failed.

**Comment by yausername** [comment]
Can you see what the error `e` is? Use android studio debugger or print stacktrace.

**Comment by UserI33X** [comment]
Disposable disposable = Observable.fromCallable(() -> {
            YoutubeDLRequest request = new YoutubeDLRequest(url);
            // best stream containing video+audio
            request.addOption("-f", "bestvideo[ext=mp4]+bestaudio[ext=m4a]/bestvideo+bestaudio", "--merge-output-format mp4");
            return YoutubeDL.getInstance().getInfo(request);
        })


I got it working but the above doesn't work Im trying to get the bestvideo and bestaudio or do I have to download the file then play it?

**Comment by UserI33X** [comment]
I think I can try to solve the issue I believe when you do bestvideo+bestaudio ffmpeg is needed and I see you provided a library for ffmpeg how would I be able to use ffmpeg in this scenario thank u.

**Comment by yausername** [comment]
Hi,
ffmpeg library can be used if you want to download bestvideo+bestaudio content.
Add it as a gradle dependency
`implementation 'com.github.yausername.youtubedl-android:ffmpeg:0.12.+'`
And intialize it like this.
```java
Fmpeg.getInstance().init(getApplication());
```

If you want to stream bestvideo+bestaudio you would need exoplayer or something. You can get the respective urls from formats list inside video info.

**Comment by UserI33X** [comment]
How would I get respective urls if u don't mind me asking?

**Comment by UserI33X** [comment]
Or do you know if exoplayer that you use in your library supports playing 2 streams at once.
