### ISSUE TITLE
java.lang.IllegalStateException: instance not initialized

### ISSUE THREAD

**Issue by shakiz** [yausername/youtubedl-android#74]
**The error:**

    `java.lang.IllegalStateException: instance not initialized
        at com.yausername.youtubedl_android.YoutubeDL.assertInit(YoutubeDL.java:118)
        at com.yausername.youtubedl_android.YoutubeDL.execute(YoutubeDL.java:150)
        at com.sakhawat.youtubedownloader.MainActivity.lambda$startDownload$0$MainActivity(MainActivity.java:120)
        at com.sakhawat.youtubedownloader.-$$Lambda$MainActivity$vnWwxuJSEPWw3MPHa9tCyEY5hXE.call(Unknown Source:4)
        at io.reactivex.internal.operators.observable.ObservableFromCallable.subscribeActual(ObservableFromCallable.java:42)
        at io.reactivex.Observable.subscribe(Observable.java:12030)
        at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:579)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)`

The line which it's referring to:
    
    `		Disposable disposable = Observable.fromCallable(() -> YoutubeDL.getInstance().execute(request, callback))
                .subscribeOn(Schedulers.newThread())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(youtubeDLResponse -> {
                    pb_status.setVisibility(View.GONE);
                    progress_bar.setProgress(100);
                    tv_status.setText(getString(R.string.download_complete));
                    tv_command_output.setText(youtubeDLResponse.getOut());
                    Toast.makeText(MainActivity.this, "Download successful", Toast.LENGTH_LONG).show();
                    downloading = false;
                }, e -> {
                    if(BuildConfig.DEBUG) Log.e("Download Error",  "Failed to download", e);
                    pb_status.setVisibility(View.GONE);
                    tv_status.setText(getString(R.string.download_failed));
                    tv_command_output.setText(e.getMessage());
                    Toast.makeText(MainActivity.this, "Download failed", Toast.LENGTH_LONG).show();
                    downloading = false;
                });
`

**Comment by yausername** [comment]
You need to initialize the instance.
```java
try {
    YoutubeDL.getInstance().init(getApplication());
} catch (YoutubeDLException e) {
    Log.e(TAG, "failed to initialize youtubedl-android", e);
}
```

**Comment by shakiz** [comment]
Ok I'll try it and will close the issue if resolved.

**Comment by shakiz** [comment]
Thanks, it is working now. So many thanks to you.
