### ISSUE TITLE
java.io.IOException: Error running exec()

### ISSUE THREAD

**Issue by LittlePWQ** [yausername/youtubedl-android#78]
When I use the install method to install the apk, everything is OK.But when I use firmware integration as a system apk, an exception occurred;  
```
com.yausername.youtubedl_android.YoutubeDLException: java.io.IOException: Error running exec(). Command: [/system/lib/OnlineMusicLibrary/libpython.bin.so, /data/data/com.evideo.onlinemusiclibrary/no_backup/youtubedl-android/youtube-dl/__main__.py, -f, best, --dump-json, --no-cache-dir, https://www.youtube.com/watch?v=b9qeohkLddA] Working Directory: null Environment: [EXTERNAL_STORAGE_FLASH=/mnt/internal_sd, ADOBE_FONTS_DIR=/system/fonts/adobefonts/, EMULATED_STORAGE_TARGET=/storage/emulated, LD_LIBRARY_PATH=/data/data/com.evideo.onlinemusiclibrary/no_backup/youtubedl-android/packages/python/usr/lib:/data/data/com.evideo.onlinemusiclibrary/no_backup/youtubedl-android/packages/ffmpeg/usr/lib, PYTHONHOME=/data/data/com.evideo.onlinemusiclibrary/no_backup/youtubedl-android/packages/python/usr, RK_ADEPT_DEVICE_TYPE=mobile, ANDROID_SOCKET_zygote=10, PATH=/sbin:/vendor/bin:/system/sbin:/system/bin:/system/xbin:/system/busybox/bin:/system/busybox/sbin:/system/lib/OnlineMusicLibrary, ANDROID_DATA=/data, BOOTCLASSPATH=/system/framework/core-libart.jar:/system/framework/conscrypt.jar:/system/framework/okhttp.jar:/system/framework/core-junit.jar:/system/framework/bouncycastle.jar:/system/framework/ext.jar:/system/framework/framework.jar:/system/framework/ims-common.jar:/system/framework/android.policy.jar:/system/framework/apache-xml.jar, RK_ADOBE_DE_MOBILE=1, RK_ADEPT_DEVICE_FILE=/mnt/sdcard/.adobe-digital-editions/device.xml, SSL_CERT_FILE=/data/data/com.evideo.onlinemusiclibrary/no_backup/youtubedl-android/packages/python/usr/etc/tls/cert.pem, ANDROID_STORAGE=/storage, RK_ADEPT_ACTIVATION_FILE=/mnt/sdcard/.adobe-digital-editions/activation.xml, EBOOK_PAGE_VISIBLE_NUMBER=2 , RK_ADOBE_DE_DOC_FOLDER=/mnt/sdcard/Digital Editions, ANDROID_ROOT=/system, EMULATED_STORAGE_SOURCE=/mnt/shell/emulated, LOOP_MOUNTPOINT=/mnt/obb, ANDROID_BOOTLOGO=1, EXTERNAL_STORAGE=/storage/emulated/legacy, SYSTEMSERVERCLASSPATH=/system/framework/services.jar:/system/framework/ethernet-service.jar:/system/framework/wifi-service.jar, SECOND_VOLUME_STORAGE=/mnt/external_sd, ANDROID_ASSETS=/system/app, RK_ADEPT_DEVICE_SALT_FILE=/mnt/sdcard/.adobe-digital-editions/devicesalt, ASEC_MOUNTPOINT=/mnt/asec, THIRD_VOLUME_STORAGE=/mnt/usb_storage, ANDROID_PROPERTY_WORKSPACE=9,0]
10-28 17:09:52.105 1732-1759/com.evideo.onlinemusiclibrary W/System.err:     at com.yausername.youtubedl_android.YoutubeDL.execute(YoutubeDL.java:179)
10-28 17:09:52.105 1732-1759/com.evideo.onlinemusiclibrary W/System.err:     at com.yausername.youtubedl_android.YoutubeDL.getInfo(YoutubeDL.java:129)
10-28 17:09:52.105 1732-1759/com.evideo.onlinemusiclibrary W/System.err:     at com.evideo.onlinemusiclibrary.present.YoutubePresent.getVideoInfo(YoutubePresent.java:397)
10-28 17:09:52.105 1732-1759/com.evideo.onlinemusiclibrary W/System.err:     at com.evideo.onlinemusiclibrary.service.YoutubeScrapperService$YtbScrapperBinder.getPlayUrl(YoutubeScrapperService.java:67)
10-28 17:09:52.105 1732-1759/com.evideo.onlinemusiclibrary W/System.err:     at com.evideo.onlinemusiclibrary.IYoutubeScrapper$Stub.onTransact(IYoutubeScrapper.java:106)
10-28 17:09:52.105 1732-1759/com.evideo.onlinemusiclibrary W/System.err: Caused by: java.io.IOException: Error running exec(). Command: [/system/lib/OnlineMusicLibrary/libpython.bin.so, /data/data/com.evideo.onlinemusiclibrary/no_backup/youtubedl-android/youtube-dl/__main__.py, -f, best, --dump-json, --no-cache-dir, https://www.youtube.com/watch?v=b9qeohkLddA] Working Directory: null Environment: [EXTERNAL_STORAGE_FLASH=/mnt/internal_sd, ADOBE_FONTS_DIR=/system/fonts/adobefonts/, EMULATED_STORAGE_TARGET=/storage/emulated, LD_LIBRARY_PATH=/data/data/com.evideo.onlinemusiclibrary/no_backup/youtubedl-android/packages/python/usr/lib:/data/data/com.evideo.onlinemusiclibrary/no_backup/youtubedl-android/packages/ffmpeg/usr/lib, PYTHONHOME=/data/data/com.evideo.onlinemusiclibrary/no_backup/youtubedl-android/packages/python/usr, RK_ADEPT_DEVICE_TYPE=mobile, ANDROID_SOCKET_zygote=10, PATH=/sbin:/vendor/bin:/system/sbin:/system/bin:/system/xbin:/system/busybox/bin:/system/busybox/sbin:/system/lib/OnlineMusicLibrary, ANDROID_DATA=/data, BOOTCLASSPATH=/system/framework/core-libart.jar:/system/framework/conscrypt.jar:/system/framework/okhttp.jar:/system/framework/core-junit.jar:/system/framework/bouncycastle.jar:/system/framework/ext.jar:/system/framework/framework.jar:/system/framework/ims-common.jar:/system/framework/android.policy.jar:/system/framework/apache-xml.jar, RK_ADOBE_DE_MOBILE=1, RK_ADEPT_DEVICE_FILE=/mnt/sdcard/.adobe-digital-editions/device.xml, SSL_CERT_FILE=/data/data/com.evideo.onlinemusiclibrary/no_backup/youtubedl-android/packages/python/usr/etc/tls/cert.pem, ANDROID_STORAGE=/storage, RK_ADEPT_ACTIVATION_FILE=/mnt/sdcard/.adobe-digital-editions/activation.xml, EBOOK_PAGE_VISIBLE_NUMBER=2 , RK_ADOBE_DE_DOC_FOLDER=/mnt/sdcard/Digital Editions, ANDROID_ROOT=/system, EMULATED_STORAGE_SOURCE=/mnt/shell/emulated, LOOP_MOUNTPOINT=/mnt/obb, ANDROID_BOOTLOGO=1, EXTERNAL_STORAGE=/storage/emulated/legacy, SYSTEMSERVERCLASSPATH=/system/framework/services.jar:/system/framework/ethernet-service.jar:/system/framework/wifi-service.jar, SECOND_VOLUME_STORAGE=/mnt/external_sd, ANDROID_ASSETS=/system/app, RK_ADEPT_DEVICE_SALT_FILE=/mnt/sdcard/.adobe-digital-editions/devicesalt, ASEC_MOUNTPOINT=/mnt/asec, THIRD_VOLUME_STORAGE=/mnt/usb_storage, ANDROID_PROPERTY_WORKSPACE=9,0]
10-28 17:09:52.106 1732-1759/com.evideo.onlinemusiclibrary W/System.err:     at com.yausername.youtubedl_android.YoutubeDL.execute(YoutubeDL.java:177)
```
How to solve this problem?

**Comment by xibr** [comment]
Hi, this is a late response, is there still an issue?
