### ISSUE TITLE
Unable to update youtube-dl

### ISSUE THREAD

**Issue by CodinGlitch** [yausername/youtubedl-android#95]
i'm very new to this so please bear that in mind.
i'm trying to update youtubedl with 
`YoutubeDL.getInstance().updateYoutubeDL(getApplication());`

the following is the error i get

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.practice, PID: 15612
    java.lang.IllegalStateException: Could not execute method for android:onClick
        at androidx.appcompat.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:414)
        at android.view.View.performClick(View.java:7277)
        at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:992)
        at android.view.View.performClickInternal(View.java:7254)
        at android.view.View.access$3600(View.java:801)
        at android.view.View$PerformClick.run(View.java:27916)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:239)
        at android.app.ActivityThread.main(ActivityThread.java:7532)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at androidx.appcompat.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:409)
        at android.view.View.performClick(View.java:7277) 
        at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:992) 
        at android.view.View.performClickInternal(View.java:7254) 
        at android.view.View.access$3600(View.java:801) 
        at android.view.View$PerformClick.run(View.java:27916) 
        at android.os.Handler.handleCallback(Handler.java:883) 
        at android.os.Handler.dispatchMessage(Handler.java:100) 
        at android.os.Looper.loop(Looper.java:239) 
        at android.app.ActivityThread.main(ActivityThread.java:7532) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935) 
     Caused by: android.os.NetworkOnMainThreadException
        at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1718)
        at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:115)
        at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
        at java.net.InetAddress.getAllByName(InetAddress.java:1152)
        at com.android.okhttp.Dns$1.lookup(Dns.java:41)
        at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:178)
        at com.android.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:144)
        at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:86)
        at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:176)
        at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
        at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:515)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:461)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:298)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:211)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:30)
        at java.net.URL.openStream(URL.java:1073)
        at com.fasterxml.jackson.core.JsonFactory._optimizedStreamFromURL(JsonFactory.java:1595)
        at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:793)
        at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2621)
        at com.yausername.youtubedl_android.YoutubeDLUpdater.checkForUpdate(YoutubeDLUpdater.java:62)
        at com.yausername.youtubedl_android.YoutubeDLUpdater.update(YoutubeDLUpdater.java:29)
        at com.yausername.youtubedl_android.YoutubeDL.updateYoutubeDL(YoutubeDL.java:214)
        at com.example.practice.MainActivity.updateYoutubeDL(MainActivity.java:84)
```

**Comment by yausername** [comment]
The error is due to method being called from main thread. You should run this method on a different thread using rx or something. Check the example in app->MainActivity.java

**Comment by CodinGlitch** [comment]
> 
> 
> The error is due to method being called from main thread. You should run this method on a different thread using rx or something. Check the example in app->MainActivity.java

thanks for the quick response, everything is working now, thanks for your help
