### ISSUE TITLE
com.yausername.youtubedl_android.YoutubeDLException: WARNING: 5QhwXoy8CT8: writing DASH m4a. Only some players support this container. Install ffmpeg or avconv to fix this automatically.     ERROR: ffprobe/avprobe and ffmpeg/avconv not found. Please install one.

### ISSUE THREAD

**Issue by riimuru** [yausername/youtubedl-android#98]
i keep getting this error when im trying to install mp3 with the following requests

    request.addOption("--extract-audio");`
    request.addOption("--audio-format");`
    request.addOption("mp3");`
    request.addOption("-o",youtubeDLDir.getAbsolutePath() + "%(id)s.%(ext)s");``

full error:

    2021-03-28 01:51:05.848 11700-11700/com.example.youtubedownloader E/YouTube DL: Failed To Download
           com.yausername.youtubedl_android.YoutubeDLException: WARNING: 5QhwXoy8CT8: writing DASH m4a. Only some 
           players support this container. Install ffmpeg or avconv to fix this automatically.
           ERROR: ffprobe/avprobe and ffmpeg/avconv not found. Please install one.
    
                 at com.yausername.youtubedl_android.YoutubeDL.execute(YoutubeDL.java:201)
                 at com.example.youtubedownloader.MainActivity$4.lambda$onClick$0$MainActivity$4(MainActivity.java:274)
                 at com.example.youtubedownloader.-$$Lambda$MainActivity$4$_6nf3K2KslWf0tugM9t10MSb0_M.call(Unknown 
                 Source:4)
                 at io.reactivex.internal.operators.observable.ObservableFromCallable.subscribeActual(ObservableFromCallable.java:42)
                 at io.reactivex.Observable.subscribe(Observable.java:12030)
                 at 
                 io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
                 at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:579)
                 at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
                 at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
                 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                 at 
                java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                at java.lang.Thread.run(Thread.java:923)`
`

**Comment by riimuru** [comment]
> Did you have added FFmpeg dependency
> 
> `implementation ​'​com.github.yausername.youtubedl-android:ffmpeg:0.12.+​'​`
> 
> also check this issue [#37](https://github.com/yausername/youtubedl-android/issues/37)

Yep

**Comment by xibr** [comment]
Also, if you still have a problem, please read the [README.md](https://github.com/yausername/youtubedl-android/blob/master/README.md) file and make sure to add these lines
![20210329-140026](https://user-images.githubusercontent.com/20098154/112821206-7443e480-9097-11eb-90f2-572ad4272219.jpg)

**Comment by riimuru** [comment]
Yep that helped alot and its fixed. Thank you
