### ISSUE TITLE
ERROR: unable to download video data: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2560)

### ISSUE THREAD

**Issue by riimuru** [yausername/youtubedl-android#99]
i keep getting this issue now from this requests
`request.addOption("-f", "best");`

full error: 

`
         2021-03-28 21:24:05.522 23386-23386/com.example.youtubedownloader E/YouTube DL: Failed To Download
    com.yausername.youtubedl_android.YoutubeDLException: ERROR: unable to download video data: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2560)`
    
        at com.yausername.youtubedl_android.YoutubeDL.execute(YoutubeDL.java:201)
        at com.example.youtubedownloader.MainActivity.lambda$null$1$MainActivity(MainActivity.java:183)
        at com.example.youtubedownloader.-$$Lambda$MainActivity$dOoUrSOY9156A_2ewgxnMJ6G4xw.call(Unknown Source:4)
        at io.reactivex.internal.operators.observable.ObservableFromCallable.subscribeActual(ObservableFromCallable.java:42)
        at io.reactivex.Observable.subscribe(Observable.java:12030)
        at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:579)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)

**Comment by riimuru** [comment]
My verbose log for comparison:
``` 2021-03-28 21:52:21.084 24373-24373/com.example.youtubedownloader E/YouTube DL: Failed To Download
    com.yausername.youtubedl_android.YoutubeDLException: [debug] System config: []
    [debug] User config: []
    [debug] Custom config: []
    [debug] Command-line args: ['-f', 'best', '--verbose', '-o', '/storage/emulated/0/Download/YouTubeDL/%(title)s.%(ext)s', '--no-cache-dir', 'https://youtu.be/nIoQMVTxyd4']
    [debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
    [debug] youtube-dl version 2021.03.25
    [debug] Lazy loading extractors enabled
    [debug] Python version 3.8.0 (CPython) - Linux-5.4.61-android11-0-00791-gbad091cc4bf3-ab6833933-i686-with-libc
    [debug] exe versions: libffmpeg.bin.so 4.2.1, libffprobe.bin.so 4.2.1
    [debug] Proxy map: {}
    ERROR: unable to download video data: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2560)
    Traceback (most recent call last):
      File "/data/data/com.example.youtubedownloader/no_backup/youtubedl-android/youtube-dl/youtube_dl/YoutubeDL.py", line 1967, in process_info
        success = dl(filename, info_dict)
      File "/data/data/com.example.youtubedownloader/no_backup/youtubedl-android/youtube-dl/youtube_dl/YoutubeDL.py", line 1906, in dl
        return fd.download(name, info)
      File "/data/data/com.example.youtubedownloader/no_backup/youtubedl-android/youtube-dl/youtube_dl/downloader/common.py", line 366, in download
        return self.real_download(filename, info_dict)
      File "/data/data/com.example.youtubedownloader/no_backup/youtubedl-android/youtube-dl/youtube_dl/downloader/http.py", line 352, in real_download
        return download()
      File "/data/data/com.example.youtubedownloader/no_backup/youtubedl-android/youtube-dl/youtube_dl/downloader/http.py", line 238, in download
        data_block = ctx.data.read(block_size if data_len is None else min(block_size, data_len - byte_counter))
      File "/data/user/0/com.example.youtubedownloader/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/http/client.py", line 454, in read
        n = self.readinto(b)
      File "/data/user/0/com.example.youtubedownloader/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/http/client.py", line 498, in readinto
        n = self.fp.readinto(b)
      File "/data/user/0/com.example.youtubedownloader/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/socket.py", line 669, in readinto
        return self._sock.recv_into(b)
      File "/data/user/0/com.example.youtubedownloader/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/ssl.py", line 1241, in recv_into
        return self.read(nbytes, buffer)
      File "/data/user/0/com.example.youtubedownloader/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/ssl.py", line 1099, in read
        return self._sslobj.read(len, buffer)
    ssl.SSLError: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2560)'``

**Comment by xibr** [comment]
Maybe this is related to youtube-dl [https://github.com/ytdl-org/youtube-dl/issues/14139](https://github.com/ytdl-org/youtube-dl/issues/14139)
 
I tried the link and it works fine for me

**Comment by xibr** [comment]
```
youtube-dl -f best https://youtu.be/nIoQMVTxyd4 -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'best', 'https://youtu.be/nIoQMVTxyd4', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.03.25
[debug] Python version 3.9.1 (CPython) - Linux-4.9.118-19869059-aarch64-with-libc
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1
[debug] Proxy map: {}
[youtube] nIoQMVTxyd4: Downloading webpage
[debug] Invoking downloader on 'https://r2---sn-o5fg5n-hjuz.googlevideo.com/videoplayback?expire=1617034011&ei=u6ZhYKO_CtKB1wb7xImwDA&ip=5.162.90.214&id=o-ALexxg_Bfmf9jRI--BoUbppvpcCi4AnvAV_xdzdvmXWy&itag=18&source=youtube&requiressl=yes&mh=j-&mm=31%2C29&mn=sn-o5fg5n-hjuz%2Csn-hju7en7k&ms=au%2Crdu&mv=m&mvi=2&pcm2cms=yes&pl=22&gcr=om&initcwndbps=356250&vprv=1&mime=video%2Fmp4&ns=mhfhj8XkHywqQk4kwDspynAF&gir=yes&clen=8226919&ratebypass=yes&dur=153.367&lmt=1593538756156729&mt=1617012281&fvip=2&fexp=24001373%2C24007246&c=WEB&txp=5531332&n=LLAux0Z1Z7rIxszMjToQ7&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgXgnXIrKCGyLy7rMyotexvH_IuS68ZUYIYJZzG-ZozIoCIA4IVl2WygePcHMcT3RXVaCwcXx-BFyhuYtQ0pgJiLT1&sig=AOq0QJ8wRAIgWzERJRCOg8ATprVK_YVoBa2qH_WYaArk8GMh7xJ_8bUCIDZKmGDGPipbJyDFIPPMk5zx3_bGuRGqvaKkjpJ2vYby'
[download] Destination: 麦吉_Maggie x 盖盖Nyan - Summertime (Arrange ver.)-nIoQMVTxyd4.mp4
[download] 100% of 7.85MiB in 00:03
```

**Comment by riimuru** [comment]
Do you know how to update the python version that was stated on the verbose log

**Comment by xibr** [comment]
You can take a look at documentation on building python for android can be seen [here](https://github.com/yausername/youtubedl-android/blob/master/BUILD_PYTHON.md). Same for ffmpeg [here](https://github.com/yausername/youtubedl-android/blob/master/BUILD_FFMPEG.md). Alternatively, you can use pre-built packages from [here (android5+)](http://termux.net/dists/stable/) or [here (android7+)](https://bintray.com/termux/termux-packages-24).

**Comment by riimuru** [comment]
Alright, I will take look thank you so much.

**Comment by sjvnnings** [comment]
I don't know if you ever got it working, but for me adding "--no-check-certification" as an option got rid of the error

**Comment by riimuru** [comment]
> I don't know if you ever got it working, but for me adding "--no-check-certification" as an option got rid of the error

thank you for your help but i already got it working

**Comment by MrGeorgeMuresan** [comment]
> 
> 
> > I don't know if you ever got it working, but for me adding "--no-check-certification" as an option got rid of the error
> 
> thank you for your help but i already got it working. if i get the error again i will try your answer

how did u fix it?

**Comment by riimuru** [comment]
> > > I don't know if you ever got it working, but for me adding "--no-check-certification" as an option got rid of the error
> > 
> > 
> > thank you for your help but i already got it working. if i get the error again i will try your answer
> 
> how did u fix it? found the fix: just add request.addOption("-f best"); to your options

thats exactly what i did lol

**Comment by hemantp66** [comment]
> 
> 
> I don't know if you ever got it working, but for me adding "--no-check-certification" as an option got rid of the error

-->>> W/System.err: __main__.py: error: no such option: --no-check-certification <<<---

Getting this error? are you sure this option works for you

**Comment by sjvnnings** [comment]
> > I don't know if you ever got it working, but for me adding "--no-check-certification" as an option got rid of the error
> 
> -->>> W/System.err: **main**.py: error: no such option: --no-check-certification <<<---
> @sjvnnings
> Getting this error? are you sure this option works for you

Just double-checked my app and it still works fine. I create a download request like normal and use
`request.addOption("--no-check-certificate")`
at the very end before executing the request.

**Comment by jddcef** [comment]
This solved it for me, believe it or not. 
It might be related to using a certain USB Dongle for wifi, it seems the common factor. Either way, some setting helped here:
> If you're having the same issue I was having, I think I've managed to resolve it using this tweak tool:
> 
> https://www.speedguide.net/downloads.php
> 
> Just use 'optimal settings' and everything should work just fine.

_Originally posted by @PyGuru100 in https://github.com/ytdl-org/youtube-dl/issues/14139#issuecomment-881227097_

**Comment by GuilhermeCouto** [comment]
how to solve on android?
